"""Video style library: 120+ styles, each with full metadata.

Fields per style:
    name, tone, visual_keywords, pacing, music_mood, voice_profile,
    hook_style, sfx_density
"""

from typing import Any, Dict, List

VIDEO_STYLES: Dict[str, Dict[str, Any]] = {
    "Cinematic": {
        "name": "Cinematic",
        "tone": "dramatic and epic",
        "visual_keywords": ["cinematic lighting", "aerial shot", "film grain", "slow motion"],
        "pacing": "slow and deliberate",
        "music_mood": ["orchestral", "epic"],
        "voice_profile": "deep authoritative male",
        "hook_style": "bold cinematic claim",
        "sfx_density": "medium",
    },
    "Anime": {
        "name": "Anime",
        "tone": "energetic and stylized",
        "visual_keywords": ["anime style scenery", "neon city night", "speed lines", "sakura petals"],
        "pacing": "fast and energetic",
        "music_mood": ["synth", "uplifting"],
        "voice_profile": "young energetic",
        "hook_style": "shocking question",
        "sfx_density": "high",
    },
    "Cyberpunk": {
        "name": "Cyberpunk",
        "tone": "gritty and futuristic",
        "visual_keywords": ["neon city", "rain soaked street", "hologram", "cyber tech"],
        "pacing": "medium and punchy",
        "music_mood": ["dark synthwave"],
        "voice_profile": "gritty adult male",
        "hook_style": "dystopian statement",
        "sfx_density": "high",
    },
    "Documentary": {
        "name": "Documentary",
        "tone": "calm and authoritative",
        "visual_keywords": ["archival footage", "landscape wide shot", "interview setup", "nature documentary"],
        "pacing": "slow and deliberate",
        "music_mood": ["ambient", "contemplative"],
        "voice_profile": "mature narrator",
        "hook_style": "surprising statistic",
        "sfx_density": "low",
    },
    "Horror": {
        "name": "Horror",
        "tone": "tense and unsettling",
        "visual_keywords": ["dark forest night", "abandoned house", "fog", "flickering light"],
        "pacing": "slow and creeping",
        "music_mood": ["dark", "suspense"],
        "voice_profile": "whispering dark",
        "hook_style": "chilling warning",
        "sfx_density": "high",
    },
    "Comedy": {
        "name": "Comedy",
        "tone": "light and playful",
        "visual_keywords": ["funny moments", "people laughing", "bright studio", "quirky objects"],
        "pacing": "fast and energetic",
        "music_mood": ["comedy", "upbeat"],
        "voice_profile": "bright friendly",
        "hook_style": "absurd claim",
        "sfx_density": "high",
    },
    "True Crime": {
        "name": "True Crime",
        "tone": "serious and suspenseful",
        "visual_keywords": ["dark alley", "police lights", "evidence board", "rainy night city"],
        "pacing": "medium and deliberate",
        "music_mood": ["tense", "minimal"],
        "voice_profile": "serious low male",
        "hook_style": "unsolved mystery hook",
        "sfx_density": "medium",
    },
    "Finance": {
        "name": "Finance",
        "tone": "confident and analytical",
        "visual_keywords": ["stock charts", "city skyline business", "trading floor", "currency"],
        "pacing": "medium and clear",
        "music_mood": ["corporate", "driving"],
        "voice_profile": "confident professional",
        "hook_style": "money statistic",
        "sfx_density": "low",
    },
    "Tech Review": {
        "name": "Tech Review",
        "tone": "clear and enthusiastic",
        "visual_keywords": ["gadget close up", "desk setup", "circuit board", "software interface"],
        "pacing": "fast and clear",
        "music_mood": ["electronic", "modern"],
        "voice_profile": "clear tech male",
        "hook_style": "product shock claim",
        "sfx_density": "medium",
    },
    "Sci-Fi": {
        "name": "Sci-Fi",
        "tone": "visionary and mysterious",
        "visual_keywords": ["space station", "futuristic city", "starfield", "alien landscape"],
        "pacing": "medium and expansive",
        "music_mood": ["ambient sci-fi"],
        "voice_profile": "calm futuristic",
        "hook_style": "future prediction",
        "sfx_density": "medium",
    },
    "Fantasy": {
        "name": "Fantasy",
        "tone": "mythic and wondrous",
        "visual_keywords": ["castle", "misty mountains", "forest magic", "medieval village"],
        "pacing": "slow and grand",
        "music_mood": ["orchestral fantasy"],
        "voice_profile": "storyteller warm",
        "hook_style": "legend opening",
        "sfx_density": "medium",
    },
    "Noir": {
        "name": "Noir",
        "tone": "cold and cynical",
        "visual_keywords": ["black and white city", "rain window", "cigarette smoke", "street lamp night"],
        "pacing": "slow and moody",
        "music_mood": ["jazz noir"],
        "voice_profile": "raspy narrator",
        "hook_style": "cynical statement",
        "sfx_density": "low",
    },
    "Retro 80s": {
        "name": "Retro 80s",
        "tone": "nostalgic and bold",
        "visual_keywords": ["retro arcade", "vhs tape", "neon grid", "80s car"],
        "pacing": "medium and groovy",
        "music_mood": ["synthwave retro"],
        "voice_profile": "upbeat retro",
        "hook_style": "nostalgia hook",
        "sfx_density": "medium",
    },
    "Vaporwave": {
        "name": "Vaporwave",
        "tone": "dreamy and surreal",
        "visual_keywords": ["pastel sunset", "greek statue", "palm trees pink", "glitch art"],
        "pacing": "slow and floaty",
        "music_mood": ["lofi", "dreamy"],
        "voice_profile": "soft dreamy",
        "hook_style": "surreal question",
        "sfx_density": "low",
    },
    "Nature": {
        "name": "Nature",
        "tone": "peaceful and awe-filled",
        "visual_keywords": ["forest canopy", "waterfall", "wildlife", "sunrise landscape"],
        "pacing": "slow and deliberate",
        "music_mood": ["ambient", "uplifting"],
        "voice_profile": "warm calm",
        "hook_style": "nature wonder fact",
        "sfx_density": "low",
    },
    "Urban": {
        "name": "Urban",
        "tone": "raw and rhythmic",
        "visual_keywords": ["city street crowd", "subway", "graffiti wall", "skyline timelapse"],
        "pacing": "fast and rhythmic",
        "music_mood": ["hip hop", "urban"],
        "voice_profile": "street casual",
        "hook_style": "street level claim",
        "sfx_density": "medium",
    },
    "Abstract": {
        "name": "Abstract",
        "tone": "poetic and detached",
        "visual_keywords": ["abstract shapes", "ink in water", "light patterns", "macro texture"],
        "pacing": "slow and hypnotic",
        "music_mood": ["ambient", "minimal"],
        "voice_profile": "soft neutral",
        "hook_style": "philosophical question",
        "sfx_density": "low",
    },
    "Surreal": {
        "name": "Surreal",
        "tone": "dreamlike and strange",
        "visual_keywords": ["floating objects", "dreamscape", "mirror reflection", "impossible architecture"],
        "pacing": "slow and odd",
        "music_mood": ["experimental ambient"],
        "voice_profile": "soft mysterious",
        "hook_style": "impossible premise",
        "sfx_density": "medium",
    },
    "Gothic": {
        "name": "Gothic",
        "tone": "dark and romantic",
        "visual_keywords": ["cathedral", "candlelight", "stone gargoyle", "fog graveyard"],
        "pacing": "slow and heavy",
        "music_mood": ["dark orchestral"],
        "voice_profile": "dark elegant",
        "hook_style": "ominous line",
        "sfx_density": "medium",
    },
    "Steampunk": {
        "name": "Steampunk",
        "tone": "inventive and adventurous",
        "visual_keywords": ["brass gears", "steam engine", "airship", "victorian workshop"],
        "pacing": "medium and mechanical",
        "music_mood": ["orchestral mechanical"],
        "voice_profile": "eccentric narrator",
        "hook_style": "invention hook",
        "sfx_density": "high",
    },
    "Dystopian": {
        "name": "Dystopian",
        "tone": "bleak and urgent",
        "visual_keywords": ["ruined city", "smog skyline", "surveillance camera", "empty streets"],
        "pacing": "medium and tense",
        "music_mood": ["dark cinematic"],
        "voice_profile": "cold serious",
        "hook_style": "warning claim",
        "sfx_density": "medium",
    },
    "Utopian": {
        "name": "Utopian",
        "tone": "hopeful and bright",
        "visual_keywords": ["green city", "solar panels", "clean architecture", "happy community"],
        "pacing": "medium and warm",
        "music_mood": ["uplifting orchestral"],
        "voice_profile": "warm optimistic",
        "hook_style": "hopeful vision",
        "sfx_density": "low",
    },
    "Vintage": {
        "name": "Vintage",
        "tone": "warm and nostalgic",
        "visual_keywords": ["old film reel", "sepia photograph", "antique objects", "1950s street"],
        "pacing": "slow and warm",
        "music_mood": ["vintage jazz"],
        "voice_profile": "warm classic",
        "hook_style": "time capsule hook",
        "sfx_density": "low",
    },
    "Neon": {
        "name": "Neon",
        "tone": "electric and vivid",
        "visual_keywords": ["neon signs", "light trails", "club lights", "reflective wet street"],
        "pacing": "fast and pulsing",
        "music_mood": ["electronic", "pulsing"],
        "voice_profile": "energetic modern",
        "hook_style": "electric claim",
        "sfx_density": "high",
    },
    "Dark Moody": {
        "name": "Dark Moody",
        "tone": "brooding and intimate",
        "visual_keywords": ["low key lighting", "shadows", "rain window", "silhouette"],
        "pacing": "slow and heavy",
        "music_mood": ["dark ambient"],
        "voice_profile": "low intimate",
        "hook_style": "brooding question",
        "sfx_density": "low",
    },
    "Bright Cheerful": {
        "name": "Bright Cheerful",
        "tone": "sunny and friendly",
        "visual_keywords": ["sunlight", "colorful flowers", "smiling people", "bright kitchen"],
        "pacing": "fast and light",
        "music_mood": ["happy acoustic"],
        "voice_profile": "bright friendly",
        "hook_style": "feel good fact",
        "sfx_density": "medium",
    },
    "Epic Trailer": {
        "name": "Epic Trailer",
        "tone": "monumental and intense",
        "visual_keywords": ["slow motion action", "storm clouds", "army marching", "mountain peak"],
        "pacing": "building and explosive",
        "music_mood": ["epic trailer drums"],
        "voice_profile": "booming trailer",
        "hook_style": "countdown hook",
        "sfx_density": "high",
    },
    "News Report": {
        "name": "News Report",
        "tone": "neutral and factual",
        "visual_keywords": ["news studio", "reporter field", "city breaking news", "press conference"],
        "pacing": "fast and clear",
        "music_mood": ["news bed", "neutral"],
        "voice_profile": "broadcast neutral",
        "hook_style": "breaking news line",
        "sfx_density": "low",
    },
    "Podcast Style": {
        "name": "Podcast Style",
        "tone": "conversational and relaxed",
        "visual_keywords": ["microphone studio", "two people talking", "cozy room", "headphones"],
        "pacing": "medium and natural",
        "music_mood": ["lofi", "chill"],
        "voice_profile": "conversational natural",
        "hook_style": "personal confession",
        "sfx_density": "low",
    },
    "Meditation": {
        "name": "Meditation",
        "tone": "gentle and soothing",
        "visual_keywords": ["calm water", "candle", "zen garden", "sunrise clouds"],
        "pacing": "very slow and calm",
        "music_mood": ["ambient", "meditative"],
        "voice_profile": "soft soothing",
        "hook_style": "gentle invitation",
        "sfx_density": "low",
    },
    "ASMR": {
        "name": "ASMR",
        "tone": "intimate and quiet",
        "visual_keywords": ["close up hands", "water droplets", "soft fabric", "macro detail"],
        "pacing": "very slow and quiet",
        "music_mood": ["ambient", "minimal"],
        "voice_profile": "whisper soft",
        "hook_style": "whispered hook",
        "sfx_density": "high",
    },
    "Mystery": {
        "name": "Mystery",
        "tone": "curious and suspenseful",
        "visual_keywords": ["fog road", "locked door", "old map", "dark library"],
        "pacing": "medium and teasing",
        "music_mood": ["mysterious", "suspense"],
        "voice_profile": "intriguing narrator",
        "hook_style": "unanswered question",
        "sfx_density": "medium",
    },
    "Thriller": {
        "name": "Thriller",
        "tone": "tense and fast",
        "visual_keywords": ["running person", "car chase", "clock ticking", "dark corridor"],
        "pacing": "fast and tense",
        "music_mood": ["tense electronic"],
        "voice_profile": "urgent male",
        "hook_style": "ticking clock hook",
        "sfx_density": "high",
    },
    "Romance": {
        "name": "Romance",
        "tone": "tender and warm",
        "visual_keywords": ["couple sunset", "candlelight dinner", "flowers", "holding hands"],
        "pacing": "slow and soft",
        "music_mood": ["romantic piano"],
        "voice_profile": "warm gentle",
        "hook_style": "emotional confession",
        "sfx_density": "low",
    },
    "Action": {
        "name": "Action",
        "tone": "explosive and driving",
        "visual_keywords": ["explosion", "stunt", "fast car", "fight scene"],
        "pacing": "very fast and punchy",
        "music_mood": ["action percussion"],
        "voice_profile": "intense male",
        "hook_style": "impact hook",
        "sfx_density": "high",
    },
    "Adventure": {
        "name": "Adventure",
        "tone": "bold and exploratory",
        "visual_keywords": ["hiking trail", "jungle expedition", "map compass", "mountain climb"],
        "pacing": "medium and driving",
        "music_mood": ["adventurous orchestral"],
        "voice_profile": "enthusiastic explorer",
        "hook_style": "journey hook",
        "sfx_density": "medium",
    },
    "Sports": {
        "name": "Sports",
        "tone": "hyped and competitive",
        "visual_keywords": ["stadium crowd", "athlete training", "slow motion goal", "running track"],
        "pacing": "fast and hyped",
        "music_mood": ["sport rock", "driving"],
        "voice_profile": "hyped announcer",
        "hook_style": "record breaking stat",
        "sfx_density": "high",
    },
    "Gaming": {
        "name": "Gaming",
        "tone": "hyper and playful",
        "visual_keywords": ["gameplay screen", "gaming setup rgb", "esports arena", "controller close up"],
        "pacing": "very fast and energetic",
        "music_mood": ["electronic", "intense"],
        "voice_profile": "excited young",
        "hook_style": "insane play claim",
        "sfx_density": "high",
    },
    "Cooking": {
        "name": "Cooking",
        "tone": "warm and inviting",
        "visual_keywords": ["cooking pan", "fresh ingredients", "chef hands", "food close up"],
        "pacing": "medium and cozy",
        "music_mood": ["acoustic", "warm"],
        "voice_profile": "friendly warm",
        "hook_style": "recipe secret hook",
        "sfx_density": "medium",
    },
    "Travel Vlog": {
        "name": "Travel Vlog",
        "tone": "breezy and personal",
        "visual_keywords": ["airport", "beach walk", "city market", "drone coastline"],
        "pacing": "medium and breezy",
        "music_mood": ["tropical", "upbeat"],
        "voice_profile": "casual friendly",
        "hook_style": "destination reveal",
        "sfx_density": "medium",
    },
    "Fitness": {
        "name": "Fitness",
        "tone": "motivating and intense",
        "visual_keywords": ["gym workout", "running outdoors", "weights", "stretching"],
        "pacing": "fast and driving",
        "music_mood": ["electronic", "motivating"],
        "voice_profile": "strong energetic",
        "hook_style": "transformation claim",
        "sfx_density": "medium",
    },
    "Fashion": {
        "name": "Fashion",
        "tone": "stylish and confident",
        "visual_keywords": ["runway", "fashion editorial", "clothing rack", "street style"],
        "pacing": "medium and rhythmic",
        "music_mood": ["fashion house beat"],
        "voice_profile": "stylish confident",
        "hook_style": "trend statement",
        "sfx_density": "medium",
    },
    "DIY": {
        "name": "DIY",
        "tone": "practical and encouraging",
        "visual_keywords": ["tools workbench", "hands crafting", "paint brush", "home project"],
        "pacing": "medium and steady",
        "music_mood": ["light acoustic"],
        "voice_profile": "helpful friendly",
        "hook_style": "before after hook",
        "sfx_density": "medium",
    },
    "Tutorial": {
        "name": "Tutorial",
        "tone": "clear and instructional",
        "visual_keywords": ["screen recording", "step by step hands", "desk workspace", "notebook"],
        "pacing": "medium and clear",
        "music_mood": ["minimal", "focused"],
        "voice_profile": "clear instructive",
        "hook_style": "promise of skill",
        "sfx_density": "low",
    },
    "Explainer": {
        "name": "Explainer",
        "tone": "friendly and logical",
        "visual_keywords": ["infographic", "whiteboard", "simple animation", "data chart"],
        "pacing": "medium and clear",
        "music_mood": ["light electronic"],
        "voice_profile": "friendly teacher",
        "hook_style": "curious why question",
        "sfx_density": "low",
    },
    "Motion Graphics": {
        "name": "Motion Graphics",
        "tone": "slick and modern",
        "visual_keywords": ["abstract motion", "geometric shapes", "kinetic typography", "gradient animation"],
        "pacing": "fast and rhythmic",
        "music_mood": ["modern electronic"],
        "voice_profile": "clean modern",
        "hook_style": "visual statement",
        "sfx_density": "medium",
    },
    "Space": {
        "name": "Space",
        "tone": "vast and awe-inspiring",
        "visual_keywords": ["galaxy", "planet surface", "spacecraft", "nebula"],
        "pacing": "slow and expansive",
        "music_mood": ["cosmic ambient"],
        "voice_profile": "deep awe narrator",
        "hook_style": "cosmic scale fact",
        "sfx_density": "low",
    },
    "Historical": {
        "name": "Historical",
        "tone": "reverent and narrative",
        "visual_keywords": ["ancient ruins", "old manuscript", "historic reenactment", "museum artifact"],
        "pacing": "slow and measured",
        "music_mood": ["classical orchestral"],
        "voice_profile": "mature narrator",
        "hook_style": "forgotten history hook",
        "sfx_density": "low",
    },
    "Astronomy": {
        "name": "Astronomy",
        "tone": "precise and wondrous",
        "visual_keywords": ["telescope", "star trails", "moon surface", "solar eclipse"],
        "pacing": "slow and clear",
        "music_mood": ["ambient cosmic"],
        "voice_profile": "calm scientific",
        "hook_style": "sky mystery hook",
        "sfx_density": "low",
    },
    "Biology": {
        "name": "Biology",
        "tone": "curious and vivid",
        "visual_keywords": ["microscope cells", "coral reef", "plant growth timelapse", "animal behavior"],
        "pacing": "medium and clear",
        "music_mood": ["light ambient"],
        "voice_profile": "curious teacher",
        "hook_style": "life fact hook",
        "sfx_density": "low",
    },
    "Physics": {
        "name": "Physics",
        "tone": "rigorous and thrilling",
        "visual_keywords": ["particle collision", "pendulum", "light refraction", "laboratory laser"],
        "pacing": "medium and precise",
        "music_mood": ["minimal electronic"],
        "voice_profile": "precise scientific",
        "hook_style": "paradox hook",
        "sfx_density": "low",
    },
    "Psychology": {
        "name": "Psychology",
        "tone": "insightful and intimate",
        "visual_keywords": ["human face close up", "brain scan", "crowd behavior", "therapy room"],
        "pacing": "medium and thoughtful",
        "music_mood": ["soft piano"],
        "voice_profile": "calm insightful",
        "hook_style": "behaviour claim",
        "sfx_density": "low",
    },
    "Philosophy": {
        "name": "Philosophy",
        "tone": "reflective and deep",
        "visual_keywords": ["statue thinker", "empty road", "candle dark", "ocean horizon"],
        "pacing": "slow and reflective",
        "music_mood": ["ambient piano"],
        "voice_profile": "thoughtful mature",
        "hook_style": "existential question",
        "sfx_density": "low",
    },
    "Motivational": {
        "name": "Motivational",
        "tone": "fiery and uplifting",
        "visual_keywords": ["sunrise runner", "mountain summit", "training montage", "crowd applause"],
        "pacing": "building and intense",
        "music_mood": ["epic uplifting"],
        "voice_profile": "powerful inspiring",
        "hook_style": "challenge to viewer",
        "sfx_density": "medium",
    },
    "Business": {
        "name": "Business",
        "tone": "sharp and credible",
        "visual_keywords": ["office meeting", "handshake", "city business district", "laptop analytics"],
        "pacing": "medium and confident",
        "music_mood": ["corporate", "driving"],
        "voice_profile": "confident professional",
        "hook_style": "market claim",
        "sfx_density": "low",
    },
    "Crypto": {
        "name": "Crypto",
        "tone": "urgent and speculative",
        "visual_keywords": ["crypto chart", "blockchain animation", "mining rig", "digital coin"],
        "pacing": "fast and urgent",
        "music_mood": ["electronic", "tense"],
        "voice_profile": "urgent analytical",
        "hook_style": "price shock claim",
        "sfx_density": "medium",
    },
    "AI & Tech": {
        "name": "AI & Tech",
        "tone": "forward-looking and crisp",
        "visual_keywords": ["ai neural network", "robot arm", "data center", "code screen"],
        "pacing": "fast and crisp",
        "music_mood": ["electronic", "futuristic"],
        "voice_profile": "clear futuristic",
        "hook_style": "ai breakthrough hook",
        "sfx_density": "medium",
    },
    "Wildlife": {
        "name": "Wildlife",
        "tone": "observant and majestic",
        "visual_keywords": ["lion savanna", "bird flight", "elephant herd", "predator hunt"],
        "pacing": "slow and majestic",
        "music_mood": ["orchestral nature"],
        "voice_profile": "documentary narrator",
        "hook_style": "animal fact hook",
        "sfx_density": "medium",
    },
    "Ocean": {
        "name": "Ocean",
        "tone": "fluid and immersive",
        "visual_keywords": ["underwater reef", "whale", "ocean waves", "deep sea"],
        "pacing": "slow and flowing",
        "music_mood": ["ambient aquatic"],
        "voice_profile": "calm deep",
        "hook_style": "ocean mystery hook",
        "sfx_density": "medium",
    },
    "Forest": {
        "name": "Forest",
        "tone": "serene and grounded",
        "visual_keywords": ["pine forest", "moss trees", "forest fog", "stream woods"],
        "pacing": "slow and calm",
        "music_mood": ["ambient organic"],
        "voice_profile": "warm calm",
        "hook_style": "forest secret hook",
        "sfx_density": "low",
    },
    "Mountain": {
        "name": "Mountain",
        "tone": "grand and stoic",
        "visual_keywords": ["snow peak", "alpine valley", "climber ridge", "mountain sunrise"],
        "pacing": "slow and grand",
        "music_mood": ["orchestral wide"],
        "voice_profile": "strong calm",
        "hook_style": "altitude fact",
        "sfx_density": "low",
    },
    "Desert": {
        "name": "Desert",
        "tone": "stark and hypnotic",
        "visual_keywords": ["sand dunes", "desert sunset", "cactus", "dust storm"],
        "pacing": "slow and sparse",
        "music_mood": ["world percussion"],
        "voice_profile": "dry calm",
        "hook_style": "survival hook",
        "sfx_density": "low",
    },
    "Arctic": {
        "name": "Arctic",
        "tone": "cold and pristine",
        "visual_keywords": ["iceberg", "polar bear", "snow storm", "frozen sea"],
        "pacing": "slow and cold",
        "music_mood": ["ambient cold"],
        "voice_profile": "calm distant",
        "hook_style": "climate fact hook",
        "sfx_density": "low",
    },
    "Volcanic": {
        "name": "Volcanic",
        "tone": "raw and dangerous",
        "visual_keywords": ["lava flow", "volcano eruption", "ash cloud", "molten rock"],
        "pacing": "medium and intense",
        "music_mood": ["dark percussive"],
        "voice_profile": "intense narrator",
        "hook_style": "eruption stat",
        "sfx_density": "high",
    },
    "Waterfall": {
        "name": "Waterfall",
        "tone": "refreshing and dynamic",
        "visual_keywords": ["waterfall drone", "river rapids", "mist rainbow", "jungle cascade"],
        "pacing": "medium and flowing",
        "music_mood": ["ambient uplifting"],
        "voice_profile": "warm calm",
        "hook_style": "scale reveal",
        "sfx_density": "medium",
    },
    "Aurora": {
        "name": "Aurora",
        "tone": "ethereal and quiet",
        "visual_keywords": ["northern lights", "night sky snow", "aurora timelapse", "stars mountains"],
        "pacing": "very slow and dreamy",
        "music_mood": ["ambient ethereal"],
        "voice_profile": "soft dreamy",
        "hook_style": "sky phenomenon hook",
        "sfx_density": "low",
    },
    "Galaxy": {
        "name": "Galaxy",
        "tone": "cosmic and immense",
        "visual_keywords": ["spiral galaxy", "deep field stars", "cosmic dust", "milky way"],
        "pacing": "slow and expansive",
        "music_mood": ["cosmic ambient"],
        "voice_profile": "deep awe narrator",
        "hook_style": "scale of universe hook",
        "sfx_density": "low",
    },
    "Nebula": {
        "name": "Nebula",
        "tone": "luminous and poetic",
        "visual_keywords": ["nebula clouds", "stellar nursery", "colorful space gas", "hubble imagery"],
        "pacing": "slow and poetic",
        "music_mood": ["ambient cosmic"],
        "voice_profile": "soft awe",
        "hook_style": "star birth hook",
        "sfx_density": "low",
    },
    "Black Hole": {
        "name": "Black Hole",
        "tone": "ominous and mind-bending",
        "visual_keywords": ["black hole render", "event horizon", "gravitational lensing", "space time"],
        "pacing": "slow and heavy",
        "music_mood": ["dark cosmic"],
        "voice_profile": "deep serious",
        "hook_style": "physics paradox hook",
        "sfx_density": "medium",
    },
    "Mars Colony": {
        "name": "Mars Colony",
        "tone": "speculative and bold",
        "visual_keywords": ["mars surface", "rover", "habitat dome", "red planet dust"],
        "pacing": "medium and forward",
        "music_mood": ["cinematic electronic"],
        "voice_profile": "clear futuristic",
        "hook_style": "colonization claim",
        "sfx_density": "medium",
    },
    "Rocket Launch": {
        "name": "Rocket Launch",
        "tone": "tense and triumphant",
        "visual_keywords": ["rocket launch", "launch pad", "booster landing", "mission control"],
        "pacing": "building and intense",
        "music_mood": ["epic electronic"],
        "voice_profile": "excited narrator",
        "hook_style": "countdown hook",
        "sfx_density": "high",
    },
    "Microscope": {
        "name": "Microscope",
        "tone": "precise and intimate",
        "visual_keywords": ["microscope slide", "bacteria", "crystal macro", "lab close up"],
        "pacing": "slow and precise",
        "music_mood": ["minimal ambient"],
        "voice_profile": "calm scientific",
        "hook_style": "invisible world hook",
        "sfx_density": "low",
    },
    "DNA": {
        "name": "DNA",
        "tone": "intricate and revealing",
        "visual_keywords": ["dna helix", "gene sequencing", "laboratory pipette", "cell division"],
        "pacing": "medium and clear",
        "music_mood": ["ambient science"],
        "voice_profile": "calm scientific",
        "hook_style": "genetic reveal hook",
        "sfx_density": "low",
    },
    "Quantum": {
        "name": "Quantum",
        "tone": "abstract and startling",
        "visual_keywords": ["quantum animation", "particle waves", "laser experiment", "abstract physics"],
        "pacing": "medium and precise",
        "music_mood": ["minimal electronic"],
        "voice_profile": "precise scientific",
        "hook_style": "counterintuitive claim",
        "sfx_density": "medium",
    },
    "Multiverse": {
        "name": "Multiverse",
        "tone": "speculative and vast",
        "visual_keywords": ["parallel worlds", "mirror dimensions", "cosmic portals", "fractal space"],
        "pacing": "slow and expansive",
        "music_mood": ["ambient cosmic"],
        "voice_profile": "mysterious narrator",
        "hook_style": "what if hook",
        "sfx_density": "medium",
    },
    "Time Travel": {
        "name": "Time Travel",
        "tone": "paradoxical and tense",
        "visual_keywords": ["clock mechanism", "time lapse city", "vortex", "old and new street"],
        "pacing": "medium and tense",
        "music_mood": ["tense orchestral"],
        "voice_profile": "mysterious narrator",
        "hook_style": "paradox hook",
        "sfx_density": "high",
    },
    "Robot": {
        "name": "Robot",
        "tone": "mechanical and curious",
        "visual_keywords": ["robot arm factory", "humanoid robot", "servo close up", "automation line"],
        "pacing": "medium and mechanical",
        "music_mood": ["electronic mechanical"],
        "voice_profile": "clear tech male",
        "hook_style": "automation claim",
        "sfx_density": "high",
    },
    "Cyborg": {
        "name": "Cyborg",
        "tone": "edgy and physical",
        "visual_keywords": ["prosthetic limb", "bionic eye", "body tech", "lab implant"],
        "pacing": "medium and edgy",
        "music_mood": ["dark electronic"],
        "voice_profile": "gritty adult male",
        "hook_style": "human upgrade hook",
        "sfx_density": "high",
    },
    "Singularity": {
        "name": "Singularity",
        "tone": "urgent and philosophical",
        "visual_keywords": ["ai server", "exponential graph", "neural network", "futuristic city"],
        "pacing": "medium and urgent",
        "music_mood": ["dark electronic"],
        "voice_profile": "serious futuristic",
        "hook_style": "timeline warning",
        "sfx_density": "medium",
    },
    "Simulation Theory": {
        "name": "Simulation Theory",
        "tone": "unsettling and clever",
        "visual_keywords": ["glitch reality", "code rain", "mirror maze", "pixel breakdown"],
        "pacing": "medium and probing",
        "music_mood": ["glitch ambient"],
        "voice_profile": "mysterious narrator",
        "hook_style": "reality doubt hook",
        "sfx_density": "high",
    },
    "UFO": {
        "name": "UFO",
        "tone": "suspicious and thrilling",
        "visual_keywords": ["night sky lights", "desert road night", "radar screen", "declassified document"],
        "pacing": "medium and teasing",
        "music_mood": ["suspense ambient"],
        "voice_profile": "intriguing narrator",
        "hook_style": "sighting hook",
        "sfx_density": "medium",
    },
    "Alien": {
        "name": "Alien",
        "tone": "speculative and eerie",
        "visual_keywords": ["alien landscape", "exoplanet", "radio telescope", "strange biology"],
        "pacing": "medium and eerie",
        "music_mood": ["ambient eerie"],
        "voice_profile": "mysterious narrator",
        "hook_style": "contact hook",
        "sfx_density": "medium",
    },
    "Cryptid": {
        "name": "Cryptid",
        "tone": "folkloric and creepy",
        "visual_keywords": ["dark woods trail", "blurry footage", "footprints mud", "foggy lake"],
        "pacing": "slow and creeping",
        "music_mood": ["dark ambient"],
        "voice_profile": "low storyteller",
        "hook_style": "legend sighting hook",
        "sfx_density": "high",
    },
    "Lost Civilization": {
        "name": "Lost Civilization",
        "tone": "archaeological and grand",
        "visual_keywords": ["jungle ruins", "stone carvings", "excavation site", "ancient temple"],
        "pacing": "slow and grand",
        "music_mood": ["world orchestral"],
        "voice_profile": "mature narrator",
        "hook_style": "vanished people hook",
        "sfx_density": "low",
    },
    "Atlantis": {
        "name": "Atlantis",
        "tone": "mythic and submerged",
        "visual_keywords": ["underwater ruins", "ancient columns", "ocean depth", "old map"],
        "pacing": "slow and mysterious",
        "music_mood": ["ambient orchestral"],
        "voice_profile": "mysterious narrator",
        "hook_style": "myth or fact hook",
        "sfx_density": "medium",
    },
    "Apocalypse": {
        "name": "Apocalypse",
        "tone": "dire and cinematic",
        "visual_keywords": ["destroyed city", "wildfire", "empty highway", "storm apocalypse"],
        "pacing": "medium and heavy",
        "music_mood": ["dark cinematic"],
        "voice_profile": "grave narrator",
        "hook_style": "doomsday claim",
        "sfx_density": "high",
    },
    "Zombie": {
        "name": "Zombie",
        "tone": "frantic and grim",
        "visual_keywords": ["abandoned hospital", "running crowd", "barricade", "dark tunnel"],
        "pacing": "fast and frantic",
        "music_mood": ["dark percussive"],
        "voice_profile": "tense narrator",
        "hook_style": "outbreak hook",
        "sfx_density": "high",
    },
    "Vampire": {
        "name": "Vampire",
        "tone": "seductive and dark",
        "visual_keywords": ["gothic castle", "blood red wine", "night city rain", "candles"],
        "pacing": "slow and seductive",
        "music_mood": ["dark orchestral"],
        "voice_profile": "dark elegant",
        "hook_style": "immortality hook",
        "sfx_density": "medium",
    },
    "Ghost": {
        "name": "Ghost",
        "tone": "hushed and eerie",
        "visual_keywords": ["empty hallway", "old mansion", "curtain wind", "dust light beam"],
        "pacing": "slow and hushed",
        "music_mood": ["eerie ambient"],
        "voice_profile": "whispering dark",
        "hook_style": "haunting hook",
        "sfx_density": "high",
    },
    "Dragon": {
        "name": "Dragon",
        "tone": "legendary and roaring",
        "visual_keywords": ["fire breath", "mountain lair", "medieval armor", "storm sky"],
        "pacing": "medium and grand",
        "music_mood": ["epic orchestral"],
        "voice_profile": "booming narrator",
        "hook_style": "myth hook",
        "sfx_density": "high",
    },
    "Phoenix": {
        "name": "Phoenix",
        "tone": "triumphant and fiery",
        "visual_keywords": ["fire embers", "sunrise flames", "bird flight", "ash rising"],
        "pacing": "building and triumphant",
        "music_mood": ["epic uplifting"],
        "voice_profile": "powerful inspiring",
        "hook_style": "rebirth hook",
        "sfx_density": "medium",
    },
    "Cosmic Horror": {
        "name": "Cosmic Horror",
        "tone": "dread-filled and vast",
        "visual_keywords": ["deep space void", "tentacle silhouette", "ancient symbols", "abyss"],
        "pacing": "slow and dreadful",
        "music_mood": ["dark drone"],
        "voice_profile": "low dread narrator",
        "hook_style": "unknowable hook",
        "sfx_density": "high",
    },
    "Psychological Horror": {
        "name": "Psychological Horror",
        "tone": "claustrophobic and quiet",
        "visual_keywords": ["empty room", "distorted mirror", "flickering bulb", "close up eye"],
        "pacing": "slow and unsettling",
        "music_mood": ["dissonant ambient"],
        "voice_profile": "low intimate",
        "hook_style": "mental unraveling hook",
        "sfx_density": "high",
    },
    "Found Footage": {
        "name": "Found Footage",
        "tone": "raw and immediate",
        "visual_keywords": ["handheld camera", "night vision", "shaky walk", "camcorder timestamp"],
        "pacing": "irregular and urgent",
        "music_mood": ["minimal tension"],
        "voice_profile": "panicked casual",
        "hook_style": "last recording hook",
        "sfx_density": "high",
    },
    "Mockumentary": {
        "name": "Mockumentary",
        "tone": "deadpan and funny",
        "visual_keywords": ["fake interview", "office setting", "awkward pause", "documentary framing"],
        "pacing": "medium and deadpan",
        "music_mood": ["quirky acoustic"],
        "voice_profile": "deadpan narrator",
        "hook_style": "absurd premise",
        "sfx_density": "medium",
    },
    "Biopic": {
        "name": "Biopic",
        "tone": "personal and reverent",
        "visual_keywords": ["archival portrait", "old letters", "historic street", "spotlight stage"],
        "pacing": "slow and narrative",
        "music_mood": ["emotional piano"],
        "voice_profile": "warm narrator",
        "hook_style": "life turning point hook",
        "sfx_density": "low",
    },
    "Alternate History": {
        "name": "Alternate History",
        "tone": "provocative and analytical",
        "visual_keywords": ["old maps", "historic flags", "period city", "archival war footage"],
        "pacing": "medium and analytical",
        "music_mood": ["tense orchestral"],
        "voice_profile": "mature narrator",
        "hook_style": "what if history hook",
        "sfx_density": "low",
    },
    "What If": {
        "name": "What If",
        "tone": "imaginative and playful",
        "visual_keywords": ["surreal composite", "simulation graphics", "earth from space", "abstract scenario"],
        "pacing": "medium and curious",
        "music_mood": ["light electronic"],
        "voice_profile": "curious teacher",
        "hook_style": "what if question",
        "sfx_density": "medium",
    },
    "Deep Dive": {
        "name": "Deep Dive",
        "tone": "thorough and immersive",
        "visual_keywords": ["research desk", "layered graphics", "library", "data visualization"],
        "pacing": "slow and thorough",
        "music_mood": ["minimal focused"],
        "voice_profile": "calm analytical",
        "hook_style": "depth promise hook",
        "sfx_density": "low",
    },
    "Breakdown": {
        "name": "Breakdown",
        "tone": "structured and sharp",
        "visual_keywords": ["diagram", "slow motion replay", "annotation graphics", "chart"],
        "pacing": "medium and structured",
        "music_mood": ["minimal driving"],
        "voice_profile": "clear analytical",
        "hook_style": "step reveal hook",
        "sfx_density": "low",
    },
    "Analysis": {
        "name": "Analysis",
        "tone": "measured and critical",
        "visual_keywords": ["charts", "comparison split screen", "notes", "market data"],
        "pacing": "medium and measured",
        "music_mood": ["corporate minimal"],
        "voice_profile": "calm analytical",
        "hook_style": "contrarian claim",
        "sfx_density": "low",
    },
    "Review": {
        "name": "Review",
        "tone": "honest and direct",
        "visual_keywords": ["product unboxing", "hands on test", "studio table", "close up detail"],
        "pacing": "medium and direct",
        "music_mood": ["light electronic"],
        "voice_profile": "friendly direct",
        "hook_style": "verdict tease",
        "sfx_density": "medium",
    },
    "Interview": {
        "name": "Interview",
        "tone": "attentive and human",
        "visual_keywords": ["two chairs studio", "microphone table", "close up listening", "soft lighting"],
        "pacing": "medium and natural",
        "music_mood": ["soft ambient"],
        "voice_profile": "conversational natural",
        "hook_style": "quote hook",
        "sfx_density": "low",
    },
    "Speech": {
        "name": "Speech",
        "tone": "commanding and rhythmic",
        "visual_keywords": ["podium", "audience crowd", "spotlight stage", "flag backdrop"],
        "pacing": "building and rhythmic",
        "music_mood": ["epic uplifting"],
        "voice_profile": "powerful inspiring",
        "hook_style": "declaration hook",
        "sfx_density": "low",
    },
    "TED Talk": {
        "name": "TED Talk",
        "tone": "polished and persuasive",
        "visual_keywords": ["red stage circle", "presenter walking", "audience listening", "slide screen"],
        "pacing": "medium and polished",
        "music_mood": ["light inspiring"],
        "voice_profile": "polished presenter",
        "hook_style": "idea hook",
        "sfx_density": "low",
    },
    "Lecture": {
        "name": "Lecture",
        "tone": "academic and steady",
        "visual_keywords": ["lecture hall", "blackboard equations", "university campus", "notebook writing"],
        "pacing": "slow and steady",
        "music_mood": ["minimal neutral"],
        "voice_profile": "calm professor",
        "hook_style": "concept hook",
        "sfx_density": "low",
    },
    "Masterclass": {
        "name": "Masterclass",
        "tone": "expert and refined",
        "visual_keywords": ["studio workshop", "expert hands", "premium lighting", "tools of craft"],
        "pacing": "medium and refined",
        "music_mood": ["cinematic minimal"],
        "voice_profile": "refined expert",
        "hook_style": "mastery promise",
        "sfx_density": "low",
    },
    "How-To": {
        "name": "How-To",
        "tone": "practical and reassuring",
        "visual_keywords": ["step demonstration", "hands close up", "tools laid out", "finished result"],
        "pacing": "medium and clear",
        "music_mood": ["light acoustic"],
        "voice_profile": "helpful friendly",
        "hook_style": "result promise",
        "sfx_density": "medium",
    },
    "Guide": {
        "name": "Guide",
        "tone": "organized and helpful",
        "visual_keywords": ["map route", "checklist", "travel planning", "screen walkthrough"],
        "pacing": "medium and organized",
        "music_mood": ["light electronic"],
        "voice_profile": "friendly teacher",
        "hook_style": "roadmap hook",
        "sfx_density": "low",
    },
    "Timeline": {
        "name": "Timeline",
        "tone": "chronological and momentum-building",
        "visual_keywords": ["clock", "historic montage", "calendar pages", "progress animation"],
        "pacing": "medium and building",
        "music_mood": ["building electronic"],
        "voice_profile": "clear narrator",
        "hook_style": "era jump hook",
        "sfx_density": "medium",
    },
    "Countdown": {
        "name": "Countdown",
        "tone": "escalating and punchy",
        "visual_keywords": ["number graphics", "ranking montage", "spotlight reveal", "fast cuts"],
        "pacing": "fast and punchy",
        "music_mood": ["building percussive"],
        "voice_profile": "hyped announcer",
        "hook_style": "number one tease",
        "sfx_density": "high",
    },
    "Quote": {
        "name": "Quote",
        "tone": "poetic and restrained",
        "visual_keywords": ["typography on texture", "slow landscape", "portrait silhouette", "paper ink"],
        "pacing": "slow and poetic",
        "music_mood": ["ambient piano"],
        "voice_profile": "soft reflective",
        "hook_style": "powerful quote hook",
        "sfx_density": "low",
    },
    "Data Story": {
        "name": "Data Story",
        "tone": "evidence-driven and clear",
        "visual_keywords": ["animated chart", "dashboard", "world map data", "spreadsheet macro"],
        "pacing": "medium and clear",
        "music_mood": ["minimal electronic"],
        "voice_profile": "calm analytical",
        "hook_style": "surprising number hook",
        "sfx_density": "low",
    },
    "Visualization": {
        "name": "Visualization",
        "tone": "abstract and elegant",
        "visual_keywords": ["particle simulation", "3d graph", "flow field", "light data lines"],
        "pacing": "medium and flowing",
        "music_mood": ["ambient electronic"],
        "voice_profile": "calm modern",
        "hook_style": "pattern reveal hook",
        "sfx_density": "low",
    },
    "Product Demo": {
        "name": "Product Demo",
        "tone": "confident and concrete",
        "visual_keywords": ["product in use", "feature close up", "clean studio", "hands interacting"],
        "pacing": "medium and confident",
        "music_mood": ["modern corporate"],
        "voice_profile": "confident professional",
        "hook_style": "problem solved hook",
        "sfx_density": "medium",
    },
    "Onboarding": {
        "name": "Onboarding",
        "tone": "welcoming and simple",
        "visual_keywords": ["app interface", "checklist ui", "friendly workspace", "hands on phone"],
        "pacing": "medium and simple",
        "music_mood": ["light friendly"],
        "voice_profile": "warm friendly",
        "hook_style": "first step promise",
        "sfx_density": "low",
    },
    "FAQ": {
        "name": "FAQ",
        "tone": "direct and efficient",
        "visual_keywords": ["question graphics", "support desk", "chat interface", "split screen answers"],
        "pacing": "fast and efficient",
        "music_mood": ["light minimal"],
        "voice_profile": "clear direct",
        "hook_style": "common question hook",
        "sfx_density": "low",
    },
    "Troubleshooting": {
        "name": "Troubleshooting",
        "tone": "calm and methodical",
        "visual_keywords": ["repair hands", "error screen", "diagnostic tools", "cable close up"],
        "pacing": "medium and methodical",
        "music_mood": ["minimal focused"],
        "voice_profile": "calm instructive",
        "hook_style": "fix promise hook",
        "sfx_density": "medium",
    },
    "Luxury": {
        "name": "Luxury",
        "tone": "refined and slow",
        "visual_keywords": ["marble surface", "luxury watch", "penthouse view", "silk fabric"],
        "pacing": "slow and refined",
        "music_mood": ["cinematic elegant"],
        "voice_profile": "refined expert",
        "hook_style": "status claim",
        "sfx_density": "low",
    },
    "Minimalist": {
        "name": "Minimalist",
        "tone": "spare and calm",
        "visual_keywords": ["white space", "single object", "soft shadow", "clean lines"],
        "pacing": "slow and spare",
        "music_mood": ["minimal ambient"],
        "voice_profile": "soft neutral",
        "hook_style": "simple truth hook",
        "sfx_density": "low",
    },
    "Street Interview": {
        "name": "Street Interview",
        "tone": "spontaneous and lively",
        "visual_keywords": ["city sidewalk", "microphone crowd", "people reacting", "urban background"],
        "pacing": "fast and lively",
        "music_mood": ["urban light beat"],
        "voice_profile": "casual friendly",
        "hook_style": "surprising answer hook",
        "sfx_density": "medium",
    },
    "Kids Educational": {
        "name": "Kids Educational",
        "tone": "cheerful and simple",
        "visual_keywords": ["colorful shapes", "toys", "playful animation", "bright classroom"],
        "pacing": "medium and cheerful",
        "music_mood": ["playful light"],
        "voice_profile": "bright friendly",
        "hook_style": "fun question hook",
        "sfx_density": "high",
    },
}


def list_styles() -> List[str]:
    """Return all style names sorted alphabetically."""
    return sorted(VIDEO_STYLES.keys())


def get_style(name: str) -> Dict[str, Any]:
    """Return a style definition, falling back to Cinematic when unknown."""
    return VIDEO_STYLES.get(name, VIDEO_STYLES["Cinematic"])


def search_styles(term: str) -> List[str]:
    """Case-insensitive search across style names and keywords."""
    term = (term or "").lower().strip()
    if not term:
        return list_styles()
    hits = []
    for name, style in VIDEO_STYLES.items():
        haystack = " ".join([name, style["tone"], " ".join(style["visual_keywords"])]).lower()
        if term in haystack:
            hits.append(name)
    return sorted(hits)


def styles_for_category(keyword: str) -> List[str]:
    """Return styles whose tone or keywords match a topical category."""
    return search_styles(keyword)


STYLE_COUNT = len(VIDEO_STYLES)
