"""Caption style library: 114 styles across 11 categories, each with a dedicated font.

Fonts are Google Fonts and are downloaded on demand by caption_renderer.py, then
cached in ./cache/fonts. Every font used here is licensed under the SIL Open Font
License or Apache 2.0 and requires no attribution inside the video.
"""

from typing import Any, Dict, List

CAPTION_STYLES: Dict[str, Dict[str, Any]] = {
    "YouTube Shorts Style": {'name': 'YouTube Shorts Style', 'category': 'platform', 'font': 'Montserrat Black', 'google_font': 'Montserrat:900', 'font_size_ratio': 0.062, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'karaoke', 'position': 'bottom', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFE600'},
    "TikTok Style": {'name': 'TikTok Style', 'category': 'platform', 'font': 'Proxima Nova Bold', 'google_font': 'Poppins:800', 'font_size_ratio': 0.055, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': 'rgba(0,0,0,0.35)', 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#FF0050'},
    "Instagram Reels Style": {'name': 'Instagram Reels Style', 'category': 'platform', 'font': 'Inter Bold', 'google_font': 'Inter:800', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#E1306C'},
    "YouTube Long-form Style": {'name': 'YouTube Long-form Style', 'category': 'platform', 'font': 'Roboto Medium', 'google_font': 'Roboto:500', 'font_size_ratio': 0.04, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.5)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Twitch Stream Style": {'name': 'Twitch Stream Style', 'category': 'platform', 'font': 'Nunito Black', 'google_font': 'Nunito:900', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#5C16C5', 'stroke_width': 5, 'background': None, 'animation': 'pop', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': True, 'highlight_color': '#9146FF'},
    "Facebook Feed Style": {'name': 'Facebook Feed Style', 'category': 'platform', 'font': 'Open Sans Bold', 'google_font': 'Open Sans:800', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': 'rgba(0,0,0,0.45)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#1877F2'},
    "LinkedIn Native Style": {'name': 'LinkedIn Native Style', 'category': 'platform', 'font': 'Source Sans Pro', 'google_font': 'Source Sans 3:600', 'font_size_ratio': 0.042, 'color': '#FFFFFF', 'stroke_color': '#0A66C2', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.55)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#0A66C2'},
    "Snapchat Spotlight Style": {'name': 'Snapchat Spotlight Style', 'category': 'platform', 'font': 'Avenir Heavy', 'google_font': 'Rubik:800', 'font_size_ratio': 0.055, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#FFFC00'},
    "Pinterest Idea Pin Style": {'name': 'Pinterest Idea Pin Style', 'category': 'platform', 'font': 'Lora Bold', 'google_font': 'Lora:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#BD081C', 'stroke_width': 4, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#BD081C'},
    "X Video Style": {'name': 'X Video Style', 'category': 'platform', 'font': 'Chirp Bold', 'google_font': 'Inter:700', 'font_size_ratio': 0.046, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': 'rgba(0,0,0,0.5)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#1D9BF0'},
    "Cinematic Captions": {'name': 'Cinematic Captions', 'category': 'genre', 'font': 'Playfair Display', 'google_font': 'Playfair Display:700', 'font_size_ratio': 0.042, 'color': '#F5F5F0', 'stroke_color': '#000000', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#D4AF37'},
    "Documentary Captions": {'name': 'Documentary Captions', 'category': 'genre', 'font': 'Lato Regular', 'google_font': 'Lato:400', 'font_size_ratio': 0.038, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 2, 'background': 'rgba(0,0,0,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 9, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Comedy Captions": {'name': 'Comedy Captions', 'category': 'genre', 'font': 'Fredoka One', 'google_font': 'Fredoka:600', 'font_size_ratio': 0.058, 'color': '#FFEB3B', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'shake', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF5722'},
    "Horror Captions": {'name': 'Horror Captions', 'category': 'genre', 'font': 'Creepster', 'google_font': 'Creepster:400', 'font_size_ratio': 0.058, 'color': '#D50000', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'glitch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF1744'},
    "Sci-Fi Captions": {'name': 'Sci-Fi Captions', 'category': 'genre', 'font': 'Orbitron', 'google_font': 'Orbitron:700', 'font_size_ratio': 0.05, 'color': '#00E5FF', 'stroke_color': '#001018', 'stroke_width': 4, 'background': None, 'animation': 'glow', 'position': 'bottom', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#00E5FF'},
    "Educational Captions": {'name': 'Educational Captions', 'category': 'genre', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.042, 'color': '#FFFFFF', 'stroke_color': '#111111', 'stroke_width': 3, 'background': 'rgba(17,17,17,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#4CAF50'},
    "Motivational Captions": {'name': 'Motivational Captions', 'category': 'genre', 'font': 'Anton', 'google_font': 'Anton:400', 'font_size_ratio': 0.066, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFC107'},
    "Music Video Captions": {'name': 'Music Video Captions', 'category': 'genre', 'font': 'Bebas Neue', 'google_font': 'Bebas Neue:400', 'font_size_ratio': 0.07, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'karaoke', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF4081'},
    "News Captions": {'name': 'News Captions', 'category': 'genre', 'font': 'Roboto Condensed', 'google_font': 'Roboto Condensed:700', 'font_size_ratio': 0.04, 'color': '#FFFFFF', 'stroke_color': '#B71C1C', 'stroke_width': 2, 'background': 'rgba(0,0,0,0.75)', 'animation': 'slide_in', 'position': 'bottom', 'uppercase': True, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Sports Captions": {'name': 'Sports Captions', 'category': 'genre', 'font': 'Teko', 'google_font': 'Teko:700', 'font_size_ratio': 0.062, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'punch', 'position': 'bottom', 'uppercase': True, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#00E676'},
    "Karaoke Highlight": {'name': 'Karaoke Highlight', 'category': 'animation', 'font': 'Montserrat Bold', 'google_font': 'Montserrat:700', 'font_size_ratio': 0.055, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'karaoke', 'position': 'bottom', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "Typewriter": {'name': 'Typewriter', 'category': 'animation', 'font': 'Source Code Pro', 'google_font': 'Source Code Pro:600', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.5)', 'animation': 'typewriter', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#00FF66'},
    "Bounce Pop": {'name': 'Bounce Pop', 'category': 'animation', 'font': 'Baloo 2', 'google_font': 'Baloo 2:800', 'font_size_ratio': 0.058, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF9800'},
    "Shake Impact": {'name': 'Shake Impact', 'category': 'animation', 'font': 'Archivo Black', 'google_font': 'Archivo Black:400', 'font_size_ratio': 0.06, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'shake', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#F44336'},
    "Glow Pulse": {'name': 'Glow Pulse', 'category': 'animation', 'font': 'Audiowide', 'google_font': 'Audiowide:400', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#00BCD4', 'stroke_width': 3, 'background': None, 'animation': 'glow', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#00E5FF'},
    "Glitch Shift": {'name': 'Glitch Shift', 'category': 'animation', 'font': 'Rubik Glitch', 'google_font': 'Rubik Glitch:400', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#FF00A8', 'stroke_width': 4, 'background': None, 'animation': 'glitch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#00FFF0'},
    "3D Transform": {'name': '3D Transform', 'category': 'animation', 'font': 'Russo One', 'google_font': 'Russo One:400', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#212121', 'stroke_width': 5, 'background': None, 'animation': 'rotate_3d', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFD54F'},
    "Particle Burst": {'name': 'Particle Burst', 'category': 'animation', 'font': 'Exo 2', 'google_font': 'Exo 2:800', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'particle', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#7C4DFF'},
    "Liquid Flow": {'name': 'Liquid Flow', 'category': 'animation', 'font': 'Comfortaa', 'google_font': 'Comfortaa:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#004D40', 'stroke_width': 4, 'background': None, 'animation': 'liquid', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#1DE9B6'},
    "Gradient Sweep": {'name': 'Gradient Sweep', 'category': 'animation', 'font': 'Poppins Bold', 'google_font': 'Poppins:700', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'gradient_sweep', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF6E7F'},
    "Word Zoom": {'name': 'Word Zoom', 'category': 'animation', 'font': 'Oswald', 'google_font': 'Oswald:600', 'font_size_ratio': 0.058, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'zoom', 'position': 'center', 'uppercase': True, 'max_words': 2, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "Slide Reveal": {'name': 'Slide Reveal', 'category': 'animation', 'font': 'Barlow', 'google_font': 'Barlow:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'slide_in', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#03A9F4'},
    "Neon Nights": {'name': 'Neon Nights', 'category': 'color', 'font': 'Audiowide', 'google_font': 'Audiowide:400', 'font_size_ratio': 0.054, 'color': '#39FF14', 'stroke_color': '#0A0A0A', 'stroke_width': 4, 'background': None, 'animation': 'glow', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF00FF'},
    "Pastel Soft": {'name': 'Pastel Soft', 'category': 'color', 'font': 'Quicksand', 'google_font': 'Quicksand:600', 'font_size_ratio': 0.048, 'color': '#FFF3F8', 'stroke_color': '#B39DDB', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': True, 'highlight_color': '#FFB7C5'},
    "Monochrome": {'name': 'Monochrome', 'category': 'color', 'font': 'Helvetica Bold', 'google_font': 'Inter:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': True, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#BDBDBD'},
    "Rainbow Pop": {'name': 'Rainbow Pop', 'category': 'color', 'font': 'Baloo 2', 'google_font': 'Baloo 2:700', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'rainbow', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF3D00'},
    "Dark Mode": {'name': 'Dark Mode', 'category': 'color', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.044, 'color': '#E0E0E0', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(18,18,18,0.8)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#BB86FC'},
    "Light Mode": {'name': 'Light Mode', 'category': 'color', 'font': 'Nunito', 'google_font': 'Nunito:700', 'font_size_ratio': 0.044, 'color': '#212121', 'stroke_color': '#FFFFFF', 'stroke_width': 3, 'background': 'rgba(255,255,255,0.85)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#1976D2'},
    "Vintage Sepia": {'name': 'Vintage Sepia', 'category': 'color', 'font': 'Playfair Display', 'google_font': 'Playfair Display:600', 'font_size_ratio': 0.046, 'color': '#F3E5AB', 'stroke_color': '#4E342E', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#C69C6D'},
    "Cyberpunk Neon": {'name': 'Cyberpunk Neon', 'category': 'color', 'font': 'Orbitron', 'google_font': 'Orbitron:800', 'font_size_ratio': 0.054, 'color': '#FCEE0A', 'stroke_color': '#FF003C', 'stroke_width': 4, 'background': None, 'animation': 'glitch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#00F0FF'},
    "Minimal White": {'name': 'Minimal White', 'category': 'color', 'font': 'Inter Light', 'google_font': 'Inter:300', 'font_size_ratio': 0.04, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Maximalist Clash": {'name': 'Maximalist Clash', 'category': 'color', 'font': 'Rubik Mono One', 'google_font': 'Rubik Mono One:400', 'font_size_ratio': 0.058, 'color': '#FFEA00', 'stroke_color': '#D500F9', 'stroke_width': 6, 'background': None, 'animation': 'shake', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#00E676'},
    "Serif Elegance": {'name': 'Serif Elegance', 'category': 'font', 'font': 'Merriweather', 'google_font': 'Merriweather:700', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#E0C097'},
    "Sans-Serif Clean": {'name': 'Sans-Serif Clean', 'category': 'font', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Script Flow": {'name': 'Script Flow', 'category': 'font', 'font': 'Dancing Script', 'google_font': 'Dancing Script:700', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'center', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FFC1E3'},
    "Display Bold": {'name': 'Display Bold', 'category': 'font', 'font': 'Alfa Slab One', 'google_font': 'Alfa Slab One:400', 'font_size_ratio': 0.06, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF7043'},
    "Monospace Terminal": {'name': 'Monospace Terminal', 'category': 'font', 'font': 'JetBrains Mono', 'google_font': 'JetBrains Mono:700', 'font_size_ratio': 0.042, 'color': '#00FF66', 'stroke_color': '#001100', 'stroke_width': 2, 'background': 'rgba(0,10,0,0.7)', 'animation': 'typewriter', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#00FF66'},
    "Handwritten Note": {'name': 'Handwritten Note', 'category': 'font', 'font': 'Caveat', 'google_font': 'Caveat:700', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'center', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FFD54F'},
    "Gothic Blackletter": {'name': 'Gothic Blackletter', 'category': 'font', 'font': 'UnifrakturMaguntia', 'google_font': 'UnifrakturMaguntia:400', 'font_size_ratio': 0.052, 'color': '#EDEDED', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#B71C1C'},
    "Retro Pixel": {'name': 'Retro Pixel', 'category': 'font', 'font': 'Press Start 2P', 'google_font': 'Press Start 2P:400', 'font_size_ratio': 0.034, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'typewriter', 'position': 'bottom', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "Futuristic Wide": {'name': 'Futuristic Wide', 'category': 'font', 'font': 'Michroma', 'google_font': 'Michroma:400', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#00838F', 'stroke_width': 3, 'background': None, 'animation': 'glow', 'position': 'bottom', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#00E5FF'},
    "Cartoon Fun": {'name': 'Cartoon Fun', 'category': 'font', 'font': 'Luckiest Guy', 'google_font': 'Luckiest Guy:400', 'font_size_ratio': 0.058, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF4081'},
    "Happy Bright": {'name': 'Happy Bright', 'category': 'emotion', 'font': 'Fredoka', 'google_font': 'Fredoka:600', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#FF6F00', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFD600'},
    "Sad Muted": {'name': 'Sad Muted', 'category': 'emotion', 'font': 'Lora', 'google_font': 'Lora:500', 'font_size_ratio': 0.044, 'color': '#CFD8DC', 'stroke_color': '#0D1B2A', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#78909C'},
    "Angry Impact": {'name': 'Angry Impact', 'category': 'emotion', 'font': 'Anton', 'google_font': 'Anton:400', 'font_size_ratio': 0.064, 'color': '#FFFFFF', 'stroke_color': '#B71C1C', 'stroke_width': 6, 'background': None, 'animation': 'shake', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF1744'},
    "Calm Breeze": {'name': 'Calm Breeze', 'category': 'emotion', 'font': 'Quicksand', 'google_font': 'Quicksand:500', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#37474F', 'stroke_width': 2, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#80DEEA'},
    "Excited Hype": {'name': 'Excited Hype', 'category': 'emotion', 'font': 'Bungee', 'google_font': 'Bungee:400', 'font_size_ratio': 0.06, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF3D00'},
    "Mysterious Veil": {'name': 'Mysterious Veil', 'category': 'emotion', 'font': 'Cinzel', 'google_font': 'Cinzel:600', 'font_size_ratio': 0.048, 'color': '#E0E0E0', 'stroke_color': '#000000', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#7E57C2'},
    "Romantic Glow": {'name': 'Romantic Glow', 'category': 'emotion', 'font': 'Great Vibes', 'google_font': 'Great Vibes:400', 'font_size_ratio': 0.058, 'color': '#FFF0F5', 'stroke_color': '#4A148C', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'center', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FF80AB'},
    "Scary Dread": {'name': 'Scary Dread', 'category': 'emotion', 'font': 'Nosifer', 'google_font': 'Nosifer:400', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#8B0000', 'stroke_width': 5, 'background': None, 'animation': 'glitch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF1744'},
    "Funny Wobble": {'name': 'Funny Wobble', 'category': 'emotion', 'font': 'Chewy', 'google_font': 'Chewy:400', 'font_size_ratio': 0.058, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'shake', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFEB3B'},
    "Serious Formal": {'name': 'Serious Formal', 'category': 'emotion', 'font': 'IBM Plex Sans', 'google_font': 'IBM Plex Sans:600', 'font_size_ratio': 0.042, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.55)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#90A4AE'},
    "Japanese Anime": {'name': 'Japanese Anime', 'category': 'culture', 'font': 'Noto Sans JP', 'google_font': 'Noto Sans JP:900', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#E91E63', 'stroke_width': 5, 'background': None, 'animation': 'pop', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF4081'},
    "Korean K-Pop": {'name': 'Korean K-Pop', 'category': 'culture', 'font': 'Noto Sans KR', 'google_font': 'Noto Sans KR:800', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'gradient_sweep', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FF80AB'},
    "Arabic Modern": {'name': 'Arabic Modern', 'category': 'culture', 'font': 'Cairo', 'google_font': 'Cairo:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#004D40', 'stroke_width': 4, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FFD54F'},
    "Chinese Bold": {'name': 'Chinese Bold', 'category': 'culture', 'font': 'Noto Sans SC', 'google_font': 'Noto Sans SC:900', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#B71C1C', 'stroke_width': 4, 'background': None, 'animation': 'pop', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#FFC107'},
    "Indian Vibrant": {'name': 'Indian Vibrant', 'category': 'culture', 'font': 'Poppins', 'google_font': 'Poppins:800', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#FF6F00', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#FFEB3B'},
    "Western Classic": {'name': 'Western Classic', 'category': 'culture', 'font': 'Rye', 'google_font': 'Rye:400', 'font_size_ratio': 0.052, 'color': '#FFF8E1', 'stroke_color': '#3E2723', 'stroke_width': 4, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#D7A86E'},
    "African Bold": {'name': 'African Bold', 'category': 'culture', 'font': 'Ultra', 'google_font': 'Ultra:400', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#1B5E20', 'stroke_width': 5, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFC107'},
    "Latin Fiesta": {'name': 'Latin Fiesta', 'category': 'culture', 'font': 'Lobster', 'google_font': 'Lobster:400', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#C62828', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#FFD600'},
    "Nordic Minimal": {'name': 'Nordic Minimal', 'category': 'culture', 'font': 'Work Sans', 'google_font': 'Work Sans:500', 'font_size_ratio': 0.042, 'color': '#FFFFFF', 'stroke_color': '#263238', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#B0BEC5'},
    "Mediterranean Warm": {'name': 'Mediterranean Warm', 'category': 'culture', 'font': 'Josefin Sans', 'google_font': 'Josefin Sans:600', 'font_size_ratio': 0.046, 'color': '#FFF8E1', 'stroke_color': '#01579B', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#4FC3F7'},
    "Tutorial Clear": {'name': 'Tutorial Clear', 'category': 'content', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#4CAF50'},
    "Review Verdict": {'name': 'Review Verdict', 'category': 'content', 'font': 'Barlow Condensed', 'google_font': 'Barlow Condensed:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'slide_in', 'position': 'bottom', 'uppercase': True, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FFC107'},
    "Vlog Casual": {'name': 'Vlog Casual', 'category': 'content', 'font': 'Nunito', 'google_font': 'Nunito:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': True, 'highlight_color': '#FF7043'},
    "Interview Lower Third": {'name': 'Interview Lower Third', 'category': 'content', 'font': 'Roboto', 'google_font': 'Roboto:500', 'font_size_ratio': 0.036, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 2, 'background': 'rgba(0,0,0,0.7)', 'animation': 'slide_in', 'position': 'bottom', 'uppercase': False, 'max_words': 9, 'emoji_default': False, 'highlight_color': '#03A9F4'},
    "Presentation Deck": {'name': 'Presentation Deck', 'category': 'content', 'font': 'Montserrat', 'google_font': 'Montserrat:600', 'font_size_ratio': 0.046, 'color': '#FFFFFF', 'stroke_color': '#1A237E', 'stroke_width': 3, 'background': 'rgba(26,35,126,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#FFD54F'},
    "Storytelling Warm": {'name': 'Storytelling Warm', 'category': 'content', 'font': 'Crimson Pro', 'google_font': 'Crimson Pro:600', 'font_size_ratio': 0.046, 'color': '#FFF3E0', 'stroke_color': '#3E2723', 'stroke_width': 3, 'background': None, 'animation': 'fade_up', 'position': 'center', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#FFB74D'},
    "Listicle Numbered": {'name': 'Listicle Numbered', 'category': 'content', 'font': 'Oswald', 'google_font': 'Oswald:600', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 5, 'background': None, 'animation': 'slide_in', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#00E676'},
    "Comparison Split": {'name': 'Comparison Split', 'category': 'content', 'font': 'Rubik', 'google_font': 'Rubik:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'slide_in', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#FF5252'},
    "Countdown Ranked": {'name': 'Countdown Ranked', 'category': 'content', 'font': 'Teko', 'google_font': 'Teko:700', 'font_size_ratio': 0.064, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 6, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "Quote Card": {'name': 'Quote Card', 'category': 'content', 'font': 'Cormorant Garamond', 'google_font': 'Cormorant Garamond:600', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#E0C097'},
    "Drop Shadow": {'name': 'Drop Shadow', 'category': 'technique', 'font': 'Inter', 'google_font': 'Inter:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 0, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Outline Only": {'name': 'Outline Only', 'category': 'technique', 'font': 'Archivo Black', 'google_font': 'Archivo Black:400', 'font_size_ratio': 0.056, 'color': '#00000000', 'stroke_color': '#FFFFFF', 'stroke_width': 5, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Solid Fill Block": {'name': 'Solid Fill Block', 'category': 'technique', 'font': 'Anton', 'google_font': 'Anton:400', 'font_size_ratio': 0.054, 'color': '#000000', 'stroke_color': '#FFEB3B', 'stroke_width': 0, 'background': '#FFEB3B', 'animation': 'pop', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#000000'},
    "Pattern Fill": {'name': 'Pattern Fill', 'category': 'technique', 'font': 'Bungee Shade', 'google_font': 'Bungee Shade:400', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'pop', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF4081'},
    "Gradient Fill": {'name': 'Gradient Fill', 'category': 'technique', 'font': 'Poppins', 'google_font': 'Poppins:800', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'gradient_sweep', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#7C4DFF'},
    "Single Stroke": {'name': 'Single Stroke', 'category': 'technique', 'font': 'Montserrat', 'google_font': 'Montserrat:800', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'karaoke', 'position': 'bottom', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "Double Stroke": {'name': 'Double Stroke', 'category': 'technique', 'font': 'Montserrat', 'google_font': 'Montserrat:900', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 8, 'background': None, 'animation': 'karaoke', 'position': 'bottom', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF1744'},
    "Emboss": {'name': 'Emboss', 'category': 'technique', 'font': 'Playfair Display', 'google_font': 'Playfair Display:800', 'font_size_ratio': 0.05, 'color': '#EFEBE9', 'stroke_color': '#5D4037', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#D7CCC8'},
    "Engrave": {'name': 'Engrave', 'category': 'technique', 'font': 'Cinzel', 'google_font': 'Cinzel:700', 'font_size_ratio': 0.048, 'color': '#BDBDBD', 'stroke_color': '#212121', 'stroke_width': 3, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#9E9E9E'},
    "Bevel Edge": {'name': 'Bevel Edge', 'category': 'technique', 'font': 'Russo One', 'google_font': 'Russo One:400', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#37474F', 'stroke_width': 4, 'background': None, 'animation': 'rotate_3d', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#B0BEC5'},
    "Y2K Chrome": {'name': 'Y2K Chrome', 'category': 'trend', 'font': 'Bungee', 'google_font': 'Bungee:400', 'font_size_ratio': 0.056, 'color': '#E8F5FF', 'stroke_color': '#3F51B5', 'stroke_width': 5, 'background': None, 'animation': 'gradient_sweep', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#00E5FF'},
    "Vaporwave Sunset": {'name': 'Vaporwave Sunset', 'category': 'trend', 'font': 'Monoton', 'google_font': 'Monoton:400', 'font_size_ratio': 0.054, 'color': '#FF77E9', 'stroke_color': '#2A0A4A', 'stroke_width': 4, 'background': None, 'animation': 'glow', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#00E5FF'},
    "Synthwave Grid": {'name': 'Synthwave Grid', 'category': 'trend', 'font': 'Audiowide', 'google_font': 'Audiowide:400', 'font_size_ratio': 0.052, 'color': '#FF2E97', 'stroke_color': '#120024', 'stroke_width': 4, 'background': None, 'animation': 'glow', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#00F0FF'},
    "Lo-Fi Chill": {'name': 'Lo-Fi Chill', 'category': 'trend', 'font': 'Space Mono', 'google_font': 'Space Mono:700', 'font_size_ratio': 0.042, 'color': '#FFF8E7', 'stroke_color': '#2B2B2B', 'stroke_width': 2, 'background': 'rgba(43,43,43,0.5)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#F4A261'},
    "Brutalist Block": {'name': 'Brutalist Block', 'category': 'trend', 'font': 'Archivo Black', 'google_font': 'Archivo Black:400', 'font_size_ratio': 0.058, 'color': '#000000', 'stroke_color': '#FFFFFF', 'stroke_width': 0, 'background': '#FFFFFF', 'animation': 'pop', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#FF0000'},
    "Glassmorphism": {'name': 'Glassmorphism', 'category': 'trend', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.046, 'color': '#FFFFFF', 'stroke_color': '#FFFFFF', 'stroke_width': 1, 'background': 'rgba(255,255,255,0.14)', 'animation': 'fade_up', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#B3E5FC'},
    "Neumorphism": {'name': 'Neumorphism', 'category': 'trend', 'font': 'Nunito', 'google_font': 'Nunito:700', 'font_size_ratio': 0.046, 'color': '#37474F', 'stroke_color': '#ECEFF1', 'stroke_width': 2, 'background': 'rgba(236,239,241,0.85)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 6, 'emoji_default': False, 'highlight_color': '#90A4AE'},
    "Claymorphism": {'name': 'Claymorphism', 'category': 'trend', 'font': 'Baloo 2', 'google_font': 'Baloo 2:700', 'font_size_ratio': 0.052, 'color': '#FFFFFF', 'stroke_color': '#8E24AA', 'stroke_width': 5, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#F48FB1'},
    "Aurora Gradient": {'name': 'Aurora Gradient', 'category': 'trend', 'font': 'Comfortaa', 'google_font': 'Comfortaa:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#0D2137', 'stroke_width': 3, 'background': None, 'animation': 'gradient_sweep', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#64FFDA'},
    "Holographic Foil": {'name': 'Holographic Foil', 'category': 'trend', 'font': 'Michroma', 'google_font': 'Michroma:400', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#4A148C', 'stroke_width': 4, 'background': None, 'animation': 'rainbow', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': False, 'highlight_color': '#B388FF'},
    "Accessibility First": {'name': 'Accessibility First', 'category': 'specialty', 'font': 'Atkinson Hyperlegible', 'google_font': 'Atkinson Hyperlegible:700', 'font_size_ratio': 0.05, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': 'rgba(0,0,0,0.8)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#FFEB3B'},
    "SEO Optimized": {'name': 'SEO Optimized', 'category': 'specialty', 'font': 'Inter', 'google_font': 'Inter:600', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 3, 'background': 'rgba(0,0,0,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 8, 'emoji_default': False, 'highlight_color': '#4CAF50'},
    "Brand Specific": {'name': 'Brand Specific', 'category': 'specialty', 'font': 'Montserrat', 'google_font': 'Montserrat:700', 'font_size_ratio': 0.048, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 4, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': True, 'max_words': 5, 'emoji_default': False, 'highlight_color': '#00BCD4'},
    "Seasonal Winter": {'name': 'Seasonal Winter', 'category': 'specialty', 'font': 'Mountains of Christmas', 'google_font': 'Mountains of Christmas:700', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#0D47A1', 'stroke_width': 4, 'background': None, 'animation': 'fade_up', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#81D4FA'},
    "Seasonal Summer": {'name': 'Seasonal Summer', 'category': 'specialty', 'font': 'Pacifico', 'google_font': 'Pacifico:400', 'font_size_ratio': 0.054, 'color': '#FFFFFF', 'stroke_color': '#F57F17', 'stroke_width': 4, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 4, 'emoji_default': True, 'highlight_color': '#FFEB3B'},
    "Event Live": {'name': 'Event Live', 'category': 'specialty', 'font': 'Teko', 'google_font': 'Teko:700', 'font_size_ratio': 0.056, 'color': '#FFFFFF', 'stroke_color': '#C62828', 'stroke_width': 5, 'background': None, 'animation': 'punch', 'position': 'bottom', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#FF5252'},
    "Podcast Waveform": {'name': 'Podcast Waveform', 'category': 'specialty', 'font': 'Space Grotesk', 'google_font': 'Space Grotesk:600', 'font_size_ratio': 0.044, 'color': '#FFFFFF', 'stroke_color': '#212121', 'stroke_width': 3, 'background': 'rgba(33,33,33,0.6)', 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#7C4DFF'},
    "Kids Friendly": {'name': 'Kids Friendly', 'category': 'specialty', 'font': 'Baloo 2', 'google_font': 'Baloo 2:800', 'font_size_ratio': 0.058, 'color': '#FFFFFF', 'stroke_color': '#4A148C', 'stroke_width': 6, 'background': None, 'animation': 'bounce', 'position': 'center', 'uppercase': False, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFEB3B'},
    "Luxury Gold": {'name': 'Luxury Gold', 'category': 'specialty', 'font': 'Cormorant Garamond', 'google_font': 'Cormorant Garamond:700', 'font_size_ratio': 0.05, 'color': '#F5E6C8', 'stroke_color': '#1A1A1A', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'center', 'uppercase': True, 'max_words': 4, 'emoji_default': False, 'highlight_color': '#D4AF37'},
    "Minimal Subtitle": {'name': 'Minimal Subtitle', 'category': 'specialty', 'font': 'Inter', 'google_font': 'Inter:400', 'font_size_ratio': 0.036, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 2, 'background': None, 'animation': 'fade', 'position': 'bottom', 'uppercase': False, 'max_words': 9, 'emoji_default': False, 'highlight_color': '#FFFFFF'},
    "Data Overlay": {'name': 'Data Overlay', 'category': 'specialty', 'font': 'IBM Plex Mono', 'google_font': 'IBM Plex Mono:600', 'font_size_ratio': 0.04, 'color': '#00E676', 'stroke_color': '#001914', 'stroke_width': 2, 'background': 'rgba(0,25,20,0.65)', 'animation': 'typewriter', 'position': 'bottom', 'uppercase': False, 'max_words': 7, 'emoji_default': False, 'highlight_color': '#00E676'},
    "MrBeast Style": {'name': 'MrBeast Style', 'category': 'specialty', 'font': 'Montserrat Black', 'google_font': 'Montserrat:900', 'font_size_ratio': 0.07, 'color': '#FFFFFF', 'stroke_color': '#000000', 'stroke_width': 8, 'background': None, 'animation': 'punch', 'position': 'center', 'uppercase': True, 'max_words': 3, 'emoji_default': True, 'highlight_color': '#FFE600'},
}

DEFAULT_CAPTION_STYLE = "YouTube Shorts Style"

CATEGORIES = sorted({style["category"] for style in CAPTION_STYLES.values()})


def list_caption_styles() -> List[str]:
    """Return every caption style name."""
    return sorted(CAPTION_STYLES.keys())


def get_caption_style(name: str) -> Dict[str, Any]:
    """Return a caption style definition with a safe default."""
    return CAPTION_STYLES.get(name, CAPTION_STYLES[DEFAULT_CAPTION_STYLE])


def styles_in_category(category: str) -> List[str]:
    """Return the caption styles that belong to a category."""
    return sorted(n for n, s in CAPTION_STYLES.items() if s["category"] == category)


# Mapping from video style to the caption style that suits it best.
VIDEO_STYLE_TO_CAPTION: Dict[str, str] = {
    "Cinematic": "Cinematic Captions",
    "Documentary": "Documentary Captions",
    "Comedy": "Comedy Captions",
    "Horror": "Horror Captions",
    "Cosmic Horror": "Scary Dread",
    "Psychological Horror": "Horror Captions",
    "Sci-Fi": "Sci-Fi Captions",
    "Cyberpunk": "Cyberpunk Neon",
    "Anime": "Japanese Anime",
    "Gaming": "Twitch Stream Style",
    "Sports": "Sports Captions",
    "News Report": "News Captions",
    "Motivational": "Motivational Captions",
    "Meditation": "Calm Breeze",
    "ASMR": "Minimal Subtitle",
    "Tutorial": "Tutorial Clear",
    "Explainer": "Educational Captions",
    "Tech Review": "Review Verdict",
    "Review": "Review Verdict",
    "Travel Vlog": "Vlog Casual",
    "Interview": "Interview Lower Third",
    "Countdown": "Countdown Ranked",
    "Quote": "Quote Card",
    "Luxury": "Luxury Gold",
    "Retro 80s": "Synthwave Grid",
    "Vaporwave": "Vaporwave Sunset",
    "Neon": "Neon Nights",
    "Kids Educational": "Kids Friendly",
    "Data Story": "Data Overlay",
    "Podcast Style": "Podcast Waveform",
    "True Crime": "Serious Formal",
    "Historical": "Serif Elegance",
    "Business": "Presentation Deck",
    "Finance": "Presentation Deck",
    "Crypto": "Data Overlay",
    "AI & Tech": "Futuristic Wide",
}


def caption_style_for_video_style(video_style: str, duration_seconds: float = 60) -> str:
    """Auto-select a caption style for a video style and duration."""
    if video_style in VIDEO_STYLE_TO_CAPTION:
        return VIDEO_STYLE_TO_CAPTION[video_style]
    return "YouTube Shorts Style" if duration_seconds < 120 else "YouTube Long-form Style"


CAPTION_STYLE_COUNT = len(CAPTION_STYLES)
