"""EdgeTTS voice library.

Every voice_id in this file was validated against the live EdgeTTS catalogue
(``edge_tts.list_voices()``): 47 English locales plus 7 multilingual voices that
speak fluent English, giving 54 fully usable voices. EdgeTTS is free and online,
so no heavy local model is involved.

Fields: voice_id, name, gender, age_range, accent, tone, moods, energy_level,
best_for, emotion_range.
"""

from typing import Any, Dict, List

VOICE_PROFILES: Dict[str, Dict[str, Any]] = {
    "en-US-AndrewNeural": {'voice_id': 'en-US-AndrewNeural', 'name': 'Andrew', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['warm', 'confident', 'natural'], 'moods': ['conversational', 'podcast', 'storytelling'], 'energy_level': 'medium', 'best_for': ['Podcast Style', 'Documentary', 'Deep Dive', 'Interview', 'Explainer', 'Analysis'], 'emotion_range': ['calm', 'warm', 'curious']},
    "en-US-AndrewMultilingualNeural": {'voice_id': 'en-US-AndrewMultilingualNeural', 'name': 'Andrew Multilingual', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['warm', 'versatile', 'natural'], 'moods': ['conversational', 'educational'], 'energy_level': 'medium', 'best_for': ['Explainer', 'Tutorial', 'Guide', 'How-To', 'Onboarding'], 'emotion_range': ['calm', 'friendly', 'curious']},
    "en-US-BrianNeural": {'voice_id': 'en-US-BrianNeural', 'name': 'Brian', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['casual', 'approachable', 'clear'], 'moods': ['conversational', 'review', 'vlog'], 'energy_level': 'medium', 'best_for': ['Review', 'Tech Review', 'Travel Vlog', 'How-To', 'Street Interview'], 'emotion_range': ['friendly', 'amused', 'curious']},
    "en-US-BrianMultilingualNeural": {'voice_id': 'en-US-BrianMultilingualNeural', 'name': 'Brian Multilingual', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['casual', 'clear', 'relaxed'], 'moods': ['conversational', 'tutorial'], 'energy_level': 'medium', 'best_for': ['Tutorial', 'FAQ', 'Troubleshooting', 'Product Demo'], 'emotion_range': ['friendly', 'calm']},
    "en-US-ChristopherNeural": {'voice_id': 'en-US-ChristopherNeural', 'name': 'Christopher', 'gender': 'male', 'age_range': 'middle-aged', 'accent': 'American', 'tone': ['authoritative', 'reliable', 'broadcast'], 'moods': ['news', 'documentary', 'business'], 'energy_level': 'medium', 'best_for': ['News Report', 'Business', 'Analysis', 'Historical', 'True Crime', 'Breakdown'], 'emotion_range': ['serious', 'neutral', 'confident']},
    "en-US-EricNeural": {'voice_id': 'en-US-EricNeural', 'name': 'Eric', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['measured', 'professional', 'neutral'], 'moods': ['corporate', 'explainer'], 'energy_level': 'low', 'best_for': ['Business', 'Data Story', 'Lecture', 'Finance', 'Visualization'], 'emotion_range': ['neutral', 'calm', 'serious']},
    "en-US-GuyNeural": {'voice_id': 'en-US-GuyNeural', 'name': 'Guy', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['energetic', 'broadcast', 'bold'], 'moods': ['trailer', 'sports', 'hype'], 'energy_level': 'high', 'best_for': ['Epic Trailer', 'Sports', 'Countdown', 'Action', 'Motivational', 'Gaming'], 'emotion_range': ['excited', 'intense', 'confident']},
    "en-US-RogerNeural": {'voice_id': 'en-US-RogerNeural', 'name': 'Roger', 'gender': 'male', 'age_range': 'middle-aged', 'accent': 'American', 'tone': ['steady', 'mature', 'grounded'], 'moods': ['documentary', 'history'], 'energy_level': 'low', 'best_for': ['Documentary', 'Historical', 'Biopic', 'Lost Civilization', 'Philosophy', 'Atlantis'], 'emotion_range': ['calm', 'reverent', 'serious']},
    "en-US-SteffanNeural": {'voice_id': 'en-US-SteffanNeural', 'name': 'Steffan', 'gender': 'male', 'age_range': 'adult', 'accent': 'American', 'tone': ['narrative', 'smooth', 'engaging'], 'moods': ['storytelling', 'audiobook'], 'energy_level': 'medium', 'best_for': ['Mystery', 'True Crime', 'Fantasy', 'Noir', 'Cryptid', 'Alternate History', 'Cinematic', 'Cosmic Horror', 'Horror', 'Psychological Horror', 'Ghost', 'Vampire', 'Dark Moody', 'Dystopian', 'Apocalypse'], 'emotion_range': ['mysterious', 'calm', 'dramatic', 'ominous']},
    "en-US-AriaNeural": {'voice_id': 'en-US-AriaNeural', 'name': 'Aria', 'gender': 'female', 'age_range': 'adult', 'accent': 'American', 'tone': ['clear', 'professional', 'polished'], 'moods': ['news', 'corporate', 'educational'], 'energy_level': 'medium', 'best_for': ['News Report', 'TED Talk', 'Presentation', 'Masterclass', 'Explainer'], 'emotion_range': ['neutral', 'confident', 'friendly']},
    "en-US-AvaNeural": {'voice_id': 'en-US-AvaNeural', 'name': 'Ava', 'gender': 'female', 'age_range': 'young-adult', 'accent': 'American', 'tone': ['bright', 'expressive', 'natural'], 'moods': ['conversational', 'lifestyle'], 'energy_level': 'medium', 'best_for': ['Travel Vlog', 'Fashion', 'Podcast Style', 'Vlog', 'Interview'], 'emotion_range': ['happy', 'curious', 'warm']},
    "en-US-AvaMultilingualNeural": {'voice_id': 'en-US-AvaMultilingualNeural', 'name': 'Ava Multilingual', 'gender': 'female', 'age_range': 'young-adult', 'accent': 'American', 'tone': ['bright', 'versatile', 'engaging'], 'moods': ['conversational', 'educational'], 'energy_level': 'medium', 'best_for': ['Tutorial', 'Explainer', 'Guide', 'Kids Educational'], 'emotion_range': ['happy', 'calm', 'curious']},
    "en-US-EmmaNeural": {'voice_id': 'en-US-EmmaNeural', 'name': 'Emma', 'gender': 'female', 'age_range': 'adult', 'accent': 'American', 'tone': ['friendly', 'warm', 'reassuring'], 'moods': ['tutorial', 'wellness'], 'energy_level': 'medium', 'best_for': ['How-To', 'Psychology', 'Kids Educational', 'DIY', 'Onboarding'], 'emotion_range': ['warm', 'calm', 'empathetic']},
    "en-US-EmmaMultilingualNeural": {'voice_id': 'en-US-EmmaMultilingualNeural', 'name': 'Emma Multilingual', 'gender': 'female', 'age_range': 'adult', 'accent': 'American', 'tone': ['friendly', 'warm', 'soothing'], 'moods': ['tutorial', 'wellness'], 'energy_level': 'low', 'best_for': ['Meditation', 'ASMR', 'Quote', 'Minimalist', 'Nature'], 'emotion_range': ['warm', 'calm', 'soothing', 'tender']},
    "en-US-JennyNeural": {'voice_id': 'en-US-JennyNeural', 'name': 'Jenny', 'gender': 'female', 'age_range': 'adult', 'accent': 'American', 'tone': ['neutral', 'versatile', 'pleasant'], 'moods': ['assistant', 'explainer', 'corporate'], 'energy_level': 'medium', 'best_for': ['Explainer', 'Guide', 'Data Story', 'FAQ', 'Comparison'], 'emotion_range': ['neutral', 'friendly', 'calm']},
    "en-US-MichelleNeural": {'voice_id': 'en-US-MichelleNeural', 'name': 'Michelle', 'gender': 'female', 'age_range': 'adult', 'accent': 'American', 'tone': ['pleasant', 'clear', 'light'], 'moods': ['lifestyle', 'tutorial'], 'energy_level': 'medium', 'best_for': ['Cooking', 'Fitness', 'DIY', 'Fashion', 'Seasonal'], 'emotion_range': ['friendly', 'cheerful']},
    "en-US-AnaNeural": {'voice_id': 'en-US-AnaNeural', 'name': 'Ana', 'gender': 'female', 'age_range': 'young', 'accent': 'American', 'tone': ['youthful', 'playful', 'light'], 'moods': ['kids', 'animation'], 'energy_level': 'high', 'best_for': ['Kids Educational', 'Comedy', 'Anime', 'Cartoon'], 'emotion_range': ['happy', 'playful', 'excited']},
    "en-GB-RyanNeural": {'voice_id': 'en-GB-RyanNeural', 'name': 'Ryan', 'gender': 'male', 'age_range': 'adult', 'accent': 'British', 'tone': ['crisp', 'confident', 'refined'], 'moods': ['documentary', 'news', 'explainer'], 'energy_level': 'medium', 'best_for': ['Documentary', 'Deep Dive', 'Analysis', 'Breakdown', 'Physics', 'Quantum'], 'emotion_range': ['neutral', 'confident', 'curious']},
    "en-GB-ThomasNeural": {'voice_id': 'en-GB-ThomasNeural', 'name': 'Thomas', 'gender': 'male', 'age_range': 'adult', 'accent': 'British', 'tone': ['formal', 'measured', 'classic'], 'moods': ['lecture', 'history', 'drama'], 'energy_level': 'low', 'best_for': ['Lecture', 'Philosophy', 'Noir', 'Gothic', 'Horror', 'Steampunk', 'Historical'], 'emotion_range': ['serious', 'calm', 'ominous']},
    "en-GB-SoniaNeural": {'voice_id': 'en-GB-SoniaNeural', 'name': 'Sonia', 'gender': 'female', 'age_range': 'adult', 'accent': 'British', 'tone': ['clear', 'elegant', 'professional'], 'moods': ['news', 'documentary'], 'energy_level': 'medium', 'best_for': ['News Report', 'Documentary', 'Fashion', 'Luxury', 'Biopic'], 'emotion_range': ['neutral', 'confident', 'refined']},
    "en-GB-LibbyNeural": {'voice_id': 'en-GB-LibbyNeural', 'name': 'Libby', 'gender': 'female', 'age_range': 'young-adult', 'accent': 'British', 'tone': ['bright', 'friendly', 'lively'], 'moods': ['lifestyle', 'tutorial'], 'energy_level': 'medium', 'best_for': ['How-To', 'Travel Vlog', 'Comedy', 'Mockumentary', 'Guide'], 'emotion_range': ['happy', 'curious', 'amused']},
    "en-GB-MaisieNeural": {'voice_id': 'en-GB-MaisieNeural', 'name': 'Maisie', 'gender': 'female', 'age_range': 'young', 'accent': 'British', 'tone': ['youthful', 'playful', 'sweet'], 'moods': ['kids', 'animation'], 'energy_level': 'high', 'best_for': ['Kids Educational', 'Anime', 'Comedy', 'Fantasy'], 'emotion_range': ['playful', 'happy', 'excited']},
    "en-AU-WilliamMultilingualNeural": {'voice_id': 'en-AU-WilliamMultilingualNeural', 'name': 'William', 'gender': 'male', 'age_range': 'adult', 'accent': 'Australian', 'tone': ['relaxed', 'warm', 'grounded'], 'moods': ['nature', 'travel', 'documentary'], 'energy_level': 'medium', 'best_for': ['Nature', 'Wildlife', 'Travel Vlog', 'Ocean', 'Adventure', 'Forest', 'Desert'], 'emotion_range': ['warm', 'calm', 'curious', 'awe']},
    "en-AU-NatashaNeural": {'voice_id': 'en-AU-NatashaNeural', 'name': 'Natasha', 'gender': 'female', 'age_range': 'adult', 'accent': 'Australian', 'tone': ['friendly', 'clear', 'easygoing'], 'moods': ['lifestyle', 'explainer'], 'energy_level': 'medium', 'best_for': ['Explainer', 'Fitness', 'Cooking', 'Biology', 'Guide'], 'emotion_range': ['friendly', 'cheerful', 'calm']},
    "en-NZ-MitchellNeural": {'voice_id': 'en-NZ-MitchellNeural', 'name': 'Mitchell', 'gender': 'male', 'age_range': 'adult', 'accent': 'New Zealander', 'tone': ['easy', 'natural', 'grounded'], 'moods': ['nature', 'travel'], 'energy_level': 'medium', 'best_for': ['Adventure', 'Mountain', 'Forest', 'Arctic', 'Waterfall'], 'emotion_range': ['calm', 'curious', 'awe']},
    "en-NZ-MollyNeural": {'voice_id': 'en-NZ-MollyNeural', 'name': 'Molly', 'gender': 'female', 'age_range': 'adult', 'accent': 'New Zealander', 'tone': ['clear', 'kind', 'bright'], 'moods': ['lifestyle', 'tutorial'], 'energy_level': 'medium', 'best_for': ['DIY', 'Cooking', 'Guide', 'Timeline'], 'emotion_range': ['friendly', 'cheerful']},
    "en-CA-LiamNeural": {'voice_id': 'en-CA-LiamNeural', 'name': 'Liam', 'gender': 'male', 'age_range': 'adult', 'accent': 'Canadian', 'tone': ['neutral', 'polite', 'clear'], 'moods': ['explainer', 'tutorial', 'tech'], 'energy_level': 'medium', 'best_for': ['Tutorial', 'Guide', 'Troubleshooting', 'Tech Review', 'AI & Tech', 'Robot', 'Cyborg'], 'emotion_range': ['calm', 'friendly', 'neutral']},
    "en-CA-ClaraNeural": {'voice_id': 'en-CA-ClaraNeural', 'name': 'Clara', 'gender': 'female', 'age_range': 'adult', 'accent': 'Canadian', 'tone': ['gentle', 'clear', 'pleasant'], 'moods': ['tutorial', 'wellness'], 'energy_level': 'medium', 'best_for': ['Onboarding', 'FAQ', 'Meditation', 'Quote', 'Minimalist'], 'emotion_range': ['calm', 'warm', 'soothing']},
    "en-IE-ConnorNeural": {'voice_id': 'en-IE-ConnorNeural', 'name': 'Connor', 'gender': 'male', 'age_range': 'adult', 'accent': 'Irish', 'tone': ['charming', 'lyrical', 'warm'], 'moods': ['storytelling', 'folklore'], 'energy_level': 'medium', 'best_for': ['Storytelling', 'Cryptid', 'Fantasy', 'Mystery', 'Dragon', 'Ghost', 'Lost Civilization'], 'emotion_range': ['mysterious', 'warm', 'amused', 'dramatic']},
    "en-IE-EmilyNeural": {'voice_id': 'en-IE-EmilyNeural', 'name': 'Emily', 'gender': 'female', 'age_range': 'adult', 'accent': 'Irish', 'tone': ['melodic', 'warm', 'engaging'], 'moods': ['storytelling', 'lifestyle'], 'energy_level': 'medium', 'best_for': ['Romance', 'Quote', 'Nature', 'Aurora', 'Vaporwave'], 'emotion_range': ['tender', 'warm', 'dreamy']},
    "en-IN-PrabhatNeural": {'voice_id': 'en-IN-PrabhatNeural', 'name': 'Prabhat', 'gender': 'male', 'age_range': 'adult', 'accent': 'Indian', 'tone': ['clear', 'instructive', 'steady'], 'moods': ['tutorial', 'tech'], 'energy_level': 'medium', 'best_for': ['Tutorial', 'AI & Tech', 'Crypto', 'Tech Review', 'Explainer'], 'emotion_range': ['neutral', 'calm', 'confident']},
    "en-IN-NeerjaNeural": {'voice_id': 'en-IN-NeerjaNeural', 'name': 'Neerja', 'gender': 'female', 'age_range': 'adult', 'accent': 'Indian', 'tone': ['warm', 'articulate', 'clear'], 'moods': ['news', 'educational'], 'energy_level': 'medium', 'best_for': ['News Report', 'Explainer', 'Business', 'Data Story'], 'emotion_range': ['neutral', 'friendly', 'calm']},
    "en-IN-NeerjaExpressiveNeural": {'voice_id': 'en-IN-NeerjaExpressiveNeural', 'name': 'Neerja Expressive', 'gender': 'female', 'age_range': 'adult', 'accent': 'Indian', 'tone': ['expressive', 'energetic', 'dynamic'], 'moods': ['motivational', 'review'], 'energy_level': 'high', 'best_for': ['Motivational', 'Countdown', 'Sports', 'Speech', 'Indian Vibrant'], 'emotion_range': ['excited', 'confident', 'inspiring']},
    "en-ZA-LukeNeural": {'voice_id': 'en-ZA-LukeNeural', 'name': 'Luke', 'gender': 'male', 'age_range': 'adult', 'accent': 'South African', 'tone': ['warm', 'rich', 'narrative'], 'moods': ['documentary', 'wildlife'], 'energy_level': 'medium', 'best_for': ['Wildlife', 'Desert', 'Documentary', 'Volcanic', 'Historical'], 'emotion_range': ['warm', 'awe', 'reverent']},
    "en-ZA-LeahNeural": {'voice_id': 'en-ZA-LeahNeural', 'name': 'Leah', 'gender': 'female', 'age_range': 'adult', 'accent': 'South African', 'tone': ['smooth', 'calm', 'clear'], 'moods': ['documentary', 'wellness'], 'energy_level': 'low', 'best_for': ['Nature', 'Meditation', 'Ocean', 'ASMR', 'Waterfall'], 'emotion_range': ['calm', 'soothing', 'tender']},
    "en-KE-ChilembaNeural": {'voice_id': 'en-KE-ChilembaNeural', 'name': 'Chilemba', 'gender': 'male', 'age_range': 'adult', 'accent': 'Kenyan', 'tone': ['resonant', 'warm', 'steady'], 'moods': ['documentary', 'storytelling'], 'energy_level': 'medium', 'best_for': ['Historical', 'Wildlife', 'Lost Civilization', 'Atlantis', 'Biopic'], 'emotion_range': ['warm', 'reverent', 'calm']},
    "en-KE-AsiliaNeural": {'voice_id': 'en-KE-AsiliaNeural', 'name': 'Asilia', 'gender': 'female', 'age_range': 'adult', 'accent': 'Kenyan', 'tone': ['bright', 'clear', 'friendly'], 'moods': ['educational', 'news'], 'energy_level': 'medium', 'best_for': ['Explainer', 'News Report', 'African Bold', 'Culture'], 'emotion_range': ['friendly', 'neutral', 'cheerful']},
    "en-NG-AbeoNeural": {'voice_id': 'en-NG-AbeoNeural', 'name': 'Abeo', 'gender': 'male', 'age_range': 'adult', 'accent': 'Nigerian', 'tone': ['bold', 'rich', 'commanding'], 'moods': ['motivational', 'speech'], 'energy_level': 'high', 'best_for': ['Speech', 'Motivational', 'Business', 'Epic Trailer', 'Phoenix'], 'emotion_range': ['confident', 'inspiring', 'intense']},
    "en-NG-EzinneNeural": {'voice_id': 'en-NG-EzinneNeural', 'name': 'Ezinne', 'gender': 'female', 'age_range': 'adult', 'accent': 'Nigerian', 'tone': ['vibrant', 'clear', 'warm'], 'moods': ['lifestyle', 'educational'], 'energy_level': 'medium', 'best_for': ['Fashion', 'Explainer', 'Urban', 'Latin Fiesta'], 'emotion_range': ['cheerful', 'warm', 'excited']},
    "en-TZ-ElimuNeural": {'voice_id': 'en-TZ-ElimuNeural', 'name': 'Elimu', 'gender': 'male', 'age_range': 'adult', 'accent': 'Tanzanian', 'tone': ['calm', 'narrative', 'warm'], 'moods': ['documentary', 'education'], 'energy_level': 'low', 'best_for': ['Documentary', 'Biology', 'Microscope', 'DNA'], 'emotion_range': ['calm', 'warm', 'curious']},
    "en-TZ-ImaniNeural": {'voice_id': 'en-TZ-ImaniNeural', 'name': 'Imani', 'gender': 'female', 'age_range': 'adult', 'accent': 'Tanzanian', 'tone': ['gentle', 'clear', 'warm'], 'moods': ['education', 'story'], 'energy_level': 'low', 'best_for': ['Kids Educational', 'Nature', 'Forest'], 'emotion_range': ['warm', 'calm', 'tender']},
    "en-SG-WayneNeural": {'voice_id': 'en-SG-WayneNeural', 'name': 'Wayne', 'gender': 'male', 'age_range': 'adult', 'accent': 'Singaporean', 'tone': ['neutral', 'crisp', 'efficient'], 'moods': ['tech', 'business'], 'energy_level': 'medium', 'best_for': ['Tech Review', 'Business', 'Data Story', 'Product Demo', 'Singularity'], 'emotion_range': ['neutral', 'confident', 'calm']},
    "en-SG-LunaNeural": {'voice_id': 'en-SG-LunaNeural', 'name': 'Luna', 'gender': 'female', 'age_range': 'adult', 'accent': 'Singaporean', 'tone': ['clear', 'efficient', 'pleasant'], 'moods': ['tech', 'tutorial'], 'energy_level': 'medium', 'best_for': ['Tutorial', 'FAQ', 'Product Demo', 'Onboarding'], 'emotion_range': ['neutral', 'friendly']},
    "en-PH-JamesNeural": {'voice_id': 'en-PH-JamesNeural', 'name': 'James', 'gender': 'male', 'age_range': 'adult', 'accent': 'Filipino', 'tone': ['friendly', 'clear', 'upbeat'], 'moods': ['vlog', 'tutorial'], 'energy_level': 'medium', 'best_for': ['Travel Vlog', 'How-To', 'Adventure'], 'emotion_range': ['friendly', 'cheerful', 'excited']},
    "en-PH-RosaNeural": {'voice_id': 'en-PH-RosaNeural', 'name': 'Rosa', 'gender': 'female', 'age_range': 'adult', 'accent': 'Filipino', 'tone': ['warm', 'bright', 'engaging'], 'moods': ['lifestyle', 'storytelling'], 'energy_level': 'medium', 'best_for': ['Cooking', 'Romance', 'Vlog', 'Seasonal'], 'emotion_range': ['warm', 'happy', 'tender']},
    "en-HK-SamNeural": {'voice_id': 'en-HK-SamNeural', 'name': 'Sam', 'gender': 'male', 'age_range': 'adult', 'accent': 'Hong Kong', 'tone': ['neutral', 'measured', 'clear'], 'moods': ['business', 'news'], 'energy_level': 'low', 'best_for': ['Business', 'Analysis', 'Finance', 'Comparison'], 'emotion_range': ['neutral', 'calm']},
    "en-HK-YanNeural": {'voice_id': 'en-HK-YanNeural', 'name': 'Yan', 'gender': 'female', 'age_range': 'adult', 'accent': 'Hong Kong', 'tone': ['clear', 'polite', 'calm'], 'moods': ['news', 'explainer'], 'energy_level': 'low', 'best_for': ['News Report', 'Explainer', 'Chinese Bold'], 'emotion_range': ['neutral', 'calm']},
    "de-DE-FlorianMultilingualNeural": {'voice_id': 'de-DE-FlorianMultilingualNeural', 'name': 'Florian', 'gender': 'male', 'age_range': 'adult', 'accent': 'European', 'tone': ['deep', 'serious', 'precise'], 'moods': ['cinematic', 'documentary', 'science'], 'energy_level': 'medium', 'best_for': ['Cinematic', 'Black Hole', 'Quantum', 'Physics', 'Dystopian', 'Cosmic Horror', 'Simulation Theory', 'Time Travel', 'Multiverse'], 'emotion_range': ['serious', 'awe', 'ominous', 'intense']},
    "de-DE-SeraphinaMultilingualNeural": {'voice_id': 'de-DE-SeraphinaMultilingualNeural', 'name': 'Seraphina', 'gender': 'female', 'age_range': 'adult', 'accent': 'European', 'tone': ['elegant', 'clear', 'composed'], 'moods': ['luxury', 'documentary'], 'energy_level': 'low', 'best_for': ['Luxury', 'Minimalist', 'Nordic Minimal', 'Astronomy', 'Nebula'], 'emotion_range': ['refined', 'calm', 'awe']},
    "fr-FR-RemyMultilingualNeural": {'voice_id': 'fr-FR-RemyMultilingualNeural', 'name': 'Remy', 'gender': 'male', 'age_range': 'adult', 'accent': 'European', 'tone': ['smooth', 'stylish', 'assured'], 'moods': ['fashion', 'lifestyle', 'cinematic'], 'energy_level': 'medium', 'best_for': ['Fashion', 'Noir', 'Romance', 'Mediterranean', 'Vintage'], 'emotion_range': ['refined', 'tender', 'dramatic']},
    "fr-FR-VivienneMultilingualNeural": {'voice_id': 'fr-FR-VivienneMultilingualNeural', 'name': 'Vivienne', 'gender': 'female', 'age_range': 'adult', 'accent': 'European', 'tone': ['poised', 'warm', 'expressive'], 'moods': ['lifestyle', 'storytelling'], 'energy_level': 'medium', 'best_for': ['Romance', 'Quote', 'Gothic', 'Surreal', 'Abstract'], 'emotion_range': ['tender', 'dreamy', 'mysterious']},
    "it-IT-GiuseppeMultilingualNeural": {'voice_id': 'it-IT-GiuseppeMultilingualNeural', 'name': 'Giuseppe', 'gender': 'male', 'age_range': 'adult', 'accent': 'European', 'tone': ['expressive', 'dramatic', 'rich'], 'moods': ['storytelling', 'trailer'], 'energy_level': 'high', 'best_for': ['Epic Trailer', 'Action', 'Adventure', 'Dragon', 'Phoenix', 'Volcanic'], 'emotion_range': ['dramatic', 'intense', 'excited']},
    "ko-KR-HyunsuMultilingualNeural": {'voice_id': 'ko-KR-HyunsuMultilingualNeural', 'name': 'Hyunsu', 'gender': 'male', 'age_range': 'young-adult', 'accent': 'Asian', 'tone': ['cool', 'modern', 'crisp'], 'moods': ['gaming', 'tech', 'music'], 'energy_level': 'high', 'best_for': ['Gaming', 'Anime', 'Cyberpunk', 'Neon', 'Korean K-Pop', 'Retro 80s', 'Vaporwave'], 'emotion_range': ['excited', 'cool', 'amused']},
    "pt-BR-ThalitaMultilingualNeural": {'voice_id': 'pt-BR-ThalitaMultilingualNeural', 'name': 'Thalita', 'gender': 'female', 'age_range': 'young-adult', 'accent': 'Latin', 'tone': ['warm', 'lively', 'expressive'], 'moods': ['lifestyle', 'vlog'], 'energy_level': 'high', 'best_for': ['Travel Vlog', 'Latin Fiesta', 'Sports', 'Fitness', 'Bright Cheerful'], 'emotion_range': ['happy', 'excited', 'warm']},
}

DEFAULT_VOICE = "en-US-AndrewNeural"


def list_voices() -> List[str]:
    """Return every voice id."""
    return list(VOICE_PROFILES.keys())


def get_voice(voice_id: str) -> Dict[str, Any]:
    """Return a voice profile, defaulting to the standard narrator voice."""
    return VOICE_PROFILES.get(voice_id, VOICE_PROFILES[DEFAULT_VOICE])


def voices_by_gender(gender: str) -> List[Dict[str, Any]]:
    """Filter voices by gender."""
    return [v for v in VOICE_PROFILES.values() if v["gender"] == gender]


def voices_by_accent(accent: str) -> List[Dict[str, Any]]:
    """Filter voices by accent."""
    return [v for v in VOICE_PROFILES.values() if v["accent"] == accent]


def voices_for_style(style_name: str) -> List[Dict[str, Any]]:
    """Return voices explicitly recommended for a video style."""
    return [v for v in VOICE_PROFILES.values() if style_name in v["best_for"]]


async def validate_against_service() -> List[str]:
    """Return any voice ids no longer offered by EdgeTTS (maintenance helper)."""
    import edge_tts

    live = {item["ShortName"] for item in await edge_tts.list_voices()}
    return [voice_id for voice_id in VOICE_PROFILES if voice_id not in live]


VOICE_COUNT = len(VOICE_PROFILES)
